### ISSUE TITLE
Fails to build on ARM/linux 4.0.7

### ISSUE THREAD

**Issue by fijam** [smuellerDD/libkcapi#1]
Perhaps I am doing something silly, but I can't figure it out. test/ fails to build on my machine

gcc --version
gcc (Debian 4.9.2-10) 4.9.2

uname -a
Linux 4.0.0-2-kirkwood #1 Debian 4.0.7-1 (2015-07-06) armv5tel GNU/Linux

make:
https://gist.github.com/fijam/72c6c347b2a3705c59bf

**Comment by smuellerDD** [comment]
Am Dienstag, 7. Juli 2015, 14:29:05 schrieb fijam:

Hi fijam,

>Perhaps I am doing something silly, but I can't figure it out.
>
>gcc --version
>gcc (Debian 4.9.2-10) 4.9.2
>
>uname -a
>Linux 4.0.0-2-kirkwood #1 Debian 4.0.7-1 (2015-07-06) armv5tel GNU/Linux
>
>make:
>https://gist.github.com/fijam/72c6c347b2a3705c59bf

Well, there seems to be multiple answers to it:

1. Did you change the Makefile? It looks like it as it includes the kernel 
headers directly which is not advisable. It should always include the C-lib 
headers from /usr/include.

2. If you use the kernel headers, was the kernel configured? It seems not as 
the compile breaks at the asm part where asm-generic/types.h and its dependent 
headers want to define u64 or s64. The used header seems to be not applicable 
for the ARM system.

The best is to use an unchanged Makefile and to have C-lib headers installed 
for compilation.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/smuellerDD/libkcapi/issues/1


Ciao
Stephan

**Comment by fijam** [comment]
Hi and thanks for the quick reply.

Sorry for not mentioning it earlier, but I modified the file to include <asm/page.h> and added the path to kernel headers as otherwise the build fails with:

gcc -Wextra -Wall -pedantic -Wno-overlength-strings -pie -fPIE -O2 -g  -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fwrapv --param ssp-buffer-size=4 -I../lib   -c -o kcapi-main.o kcapi-main.c
kcapi-main.c: In function ‘cavs_sym’:
kcapi-main.c:408:39: error: ‘PAGE_SIZE’ undeclared (first use in this function)
   if (posix_memalign((void *)&outbuf, PAGE_SIZE, outbuflen))
                                       ^
kcapi-main.c:408:39: note: each undeclared identifier is reported only once for each function it appears in
kcapi-main.c: In function ‘cavs_sym_stream’:
kcapi-main.c:488:39: error: ‘PAGE_SIZE’ undeclared (first use in this function)
   if (posix_memalign((void *)&outbuf, PAGE_SIZE, outbuflen))
                                       ^
kcapi-main.c: In function ‘cavs_aead’:
kcapi-main.c:626:39: error: ‘PAGE_SIZE’ undeclared (first use in this function)
   if (posix_memalign((void *)&outbuf, PAGE_SIZE, outbuflen))
                                       ^
kcapi-main.c: In function ‘cavs_aead_stream’:
kcapi-main.c:780:39: error: ‘PAGE_SIZE’ undeclared (first use in this function)
   if (posix_memalign((void *)&outbuf, PAGE_SIZE, outbuflen))
                                       ^
kcapi-main.c: In function ‘cavs_aead_large’:
kcapi-main.c:989:42: error: ‘PAGE_SIZE’ undeclared (first use in this function)
  if (posix_memalign((void *)&test.assoc, PAGE_SIZE, (16 * PAGE_SIZE)))
                                          ^
<builtin>: recipe for target 'kcapi-main.o' failed
make: *** [kcapi-main.o] Error 1

I thought PAGE_SIZE is only provided by page.h from the kernel, but it seems that was the wrong assumption?

**Comment by smuellerDD** [comment]
Am Mittwoch, 8. Juli 2015, 00:53:56 schrieb fijam:

Hi fijam,

>Hi and thanks for the quick reply.
>
>Sorry for not mentioning it earlier, but I modified the file to include
><asm/page.h> and added the path to kernel headers as otherwise the build
>fails with:
>
>gcc -Wextra -Wall -pedantic -Wno-overlength-strings -pie -fPIE -O2 -g 
>-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fwrapv --param
>ssp-buffer-size=4 -I../lib   -c -o kcapi-main.o kcapi-main.c kcapi-main.c:
>In function ‘cavs_sym’:
>kcapi-main.c:408:39: error: ‘PAGE_SIZE’ undeclared (first use in this
>function) if (posix_memalign((void *)&outbuf, PAGE_SIZE, outbuflen))
>                                       ^
>kcapi-main.c:408:39: note: each undeclared identifier is reported only once
>for each function it appears in kcapi-main.c: In function ‘cavs_sym_stream’:
>kcapi-main.c:488:39: error: ‘PAGE_SIZE’ undeclared (first use in this
>function) if (posix_memalign((void *)&outbuf, PAGE_SIZE, outbuflen))
>                                       ^
>kcapi-main.c: In function ‘cavs_aead’:
>kcapi-main.c:626:39: error: ‘PAGE_SIZE’ undeclared (first use in this
>function) if (posix_memalign((void *)&outbuf, PAGE_SIZE, outbuflen))
>                                       ^
>kcapi-main.c: In function ‘cavs_aead_stream’:
>kcapi-main.c:780:39: error: ‘PAGE_SIZE’ undeclared (first use in this
>function) if (posix_memalign((void *)&outbuf, PAGE_SIZE, outbuflen))
>                                       ^
>kcapi-main.c: In function ‘cavs_aead_large’:
>kcapi-main.c:989:42: error: ‘PAGE_SIZE’ undeclared (first use in this
>function) if (posix_memalign((void *)&test.assoc, PAGE_SIZE, (16 *
>PAGE_SIZE))) ^
><builtin>: recipe for target 'kcapi-main.o' failed
>make: *** [kcapi-main.o] Error 1
>
>I thought PAGE_SIZE is only provided by page.h from the kernel, but it seems
>that was the wrong assumption?

Rule of thumb: never link with the kernel includes directly. And if you must, 
then only with the uapi/ includes.

I am wondering why your Clib does not define it. Can you please grep your 
/usr/include tree to see where it is? If you find it, can you please let me 
know which include must be pulled?

In any case, it is better to take this one definition out of the kernel and 
into a private header file.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/smuellerDD/libkcapi/issues/1#issuecomment-119476746


Ciao
Stephan

**Comment by fijam** [comment]
Apparently the PAGE_SIZE macro is not available on my platform. As a workaround I added 

#define PAGE_SIZE sysconf(_SC_PAGESIZE)

and now it builds correctly.
