### ISSUE TITLE
Make pdf command didn't work

### ISSUE THREAD

**Issue by haohaole1230** [smuellerDD/libkcapi#104]
I followed the readme file to install libkcapi libs, but when I started to run "make pdf", it just didn't work. I have installed xmlto libs and db2dpf libs. I opened the makefile and find that the command after pdf target is blank:
pdf: pdf-am

pdf-am:
I don't know where to read the doc?
Thank you

**Comment by smuellerDD** [comment]
Well, db2pdf libs will not help, you need the db2pdf application. On Fedora, this is in the RPM docbook-utils-pdf

**Comment by smuellerDD** [comment]
Am Dienstag, 9. März 2021, 08:49:59 CET schrieb shihaohao132:

Hi shihaohao132,

> Hi smueller, I'm a new user of libcapi, I try to run the application demo of
> test folder and read the codes of demo . But I don't find the any user
> guide doc to use these demo. For example: If I want to use the RSA function
> to sign my file, how should I configure the parameters of main function? Do
> you know how could I find the related user guide to understand the codes?
> Thank you very much.

The test code is, well, test code and not intended as a pure demo code. 
Though, kcapi-main.c implements all API calls and all use cases of the APIs 
and thus could be mined for information.

The full complete test run is invoked with test-invocation.sh.

If you want to start, you may want to check kcapi-main.c, functions cavs_hash, 
cavs_sym, cavs_aead.

Ciao
Stephan
