### ISSUE TITLE
Find license for this source code

### ISSUE THREAD

**Issue by Traicopki** [smuellerDD/libkcapi#105]
Dear all,
When I find license of this source, I found text "License: see LICENSE file in root directory" in https://github.com/smuellerDD/libkcapi/blob/master/apps/app-internal.c
But, I don't see LICENSE file.
Please let me know about this LICENSE file.

**Comment by smuellerDD** [comment]
Ah, yes that is a slight inconsistency. The intended files are the COPYING* files in the root dir. Eventually I will update that.
