### ISSUE TITLE
No user guide to run demo application

### ISSUE THREAD

**Issue by haohaole1230** [smuellerDD/libkcapi#106]
Hi smueller, I'm a new user of libcapi, I try to run the application demo of test folder and read the codes of demo . But I don't find the any user guide doc to use these demo. For example: If I want to use the RSA function to sign my file, how should I configure the parameters of main function? Do you know how could I find the related user guide to understand the codes? Thank you very much.

**Comment by smuellerDD** [comment]
Am Dienstag, dem 09.03.2021 um 01:22 -0800 schrieb shihaohao132:
> Well, I have tried to make man, but it didn't work. 
> make: *** No rule to make target 'man'.  Stop.
> I opened the makefile, there were really no man target to compile. I also
> try to uncomment the code of man: man-stamp, it also didn't work
> 

The entire documentation of the man pages is derived from kcapi.h.

Ciao
Stephan
