### ISSUE TITLE
Linking to libkcapi prevents applications being debugged with gdb

### ISSUE THREAD

**Issue by ueno** [smuellerDD/libkcapi#109]
I noticed that the library constructor calls [prctl(PR_SET_DUMPABLE, 0)](https://github.com/smuellerDD/libkcapi/blob/master/lib/kcapi-kernel-if.c#L1392) unconditionally. That makes any linked applications impossible to be debugged with gdb, because the process cannot be attached via `ptrace`. I suppose this has already been well considered, but could that be relaxed a bit, e.g., by protecting only relevant pages with `madvise(MADV_DONTDUMP)`?

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 18.03.2021 um 08:14 -0700 schrieb Daiki Ueno:
> I noticed that the library constructor calls [prctl(PR_SET_DUMPABLE,
> 0)](https://github.com/smuellerDD/libkcapi/blob/master/lib/kcapi-kernel-if.c#L1392
> ) unconditionally. That makes any linked applications impossible to be
> debugged with gdb, because the process cannot be attached via `ptrace`. I
> suppose this has already been well considered, but could this be relaxed a
> bit, e.g., by protecting only relevant pages with `madvise(MADV_DONTDUMP)`?
> 
I usually compile the library with make debug when I want to debug it.

How do you view the dumpable protection in your projects? I mean I do not want
to protect debugging. But a crypto library should not simply dump its core.

Thanks
Stephan

**Comment by ueno** [comment]
I generally agree that crypto libraries shouldn't dump sensitive data to its core. Let me clarify my concern a bit: I'm thinking to enable AF_ALG support in a GnuTLS distro package through libkcapi, once the current [patches](https://gitlab.com/gnutls/gnutls/-/merge_requests/1404) are ready. I worry that it could make any consumers of the package (e.g., GNOME applications) non-debuggable, even when the user wants to track issues in non-crypto code.

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 18.03.2021 um 09:28 -0700 schrieb Daiki Ueno:


So, you do not have similar protection mechanisms in GnuTLS? I also do not see
similar code in other crypto libs like libgcrypt, OpenSSL or NSS. So maybe I
am a bit over-zealous here?!

Ciao
Stephan

**Comment by ueno** [comment]
> So, you do not have similar protection mechanisms in GnuTLS?

No, we don't. Afaik, gnome-keyring and libsecret make use of `MADV_DONTDUMP` for sensitive data but not for the entire process memory. I might open an issue against GnuTLS to do similar :-)

**Comment by smuellerDD** [comment]
After some study, I verified that libkcapi does not hold sensitive data. Thus, I removed the prctl flag for good.

But as soon as sensitive data is added, I will use MADV_DONTDUMP and mlock.

**Comment by ueno** [comment]
Thank you!
