### ISSUE TITLE
SONAME bump?

### ISSUE THREAD

**Issue by WOnder93** [smuellerDD/libkcapi#115]
Since commit 50b3ba132d22 changed the signatures of many public libkcapi functions, shouldn't this be accompanied by an SONAME bump of the library? Looking at the build scripts, it seems this would be achieved by bumping the major version.

I'm not aware of any packages at least in Fedora that would link against libkcapi, but still it would be better to follow the correct procedure.

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 20.05.2021 um 01:57 -0700 schrieb Ondrej Mosnáček:
> Since commit 50b3ba132d22 changed the signatures of many public libkcapi
> functions, shouldn't this be accompanied by an SONAME bump of the library?
> Looking at the build scripts, it seems this would be achieved by bumping the
> major version.

A change in the major version would be counter to the rules I like to apply.
See configure.ac:

dnl KCAPI_MAJVERSION API / ABI incompatible changes, functional
dnl                  changes that require consumer to be updated
dnl                  (as long as this number is zero, the API is
dnl                  not considered stable and can change without
dnl                  a bump of the major version)
dnl KCAPI_MINVERSION API compatible, ABI may change, functional
dnl                  enhancements only, consumer can be left
dnl                  unchanged if enhancements are not considered
dnl KCAPI_PATCHLEVEL API / ABI compatible, no functional changes, no
dnl                  enhancements, bug fixes only. Versions with
dnl                  a decimal point are pre-releases.

We surely have an ABI change, but no API change.

What about using the minor version in the SONAME as well?

Ciao
Stephan

**Comment by WOnder93** [comment]
I'd say it is a bit API-inompatible, too, since it can cause at least new compiler warnings with -Wconversion... but maybe that's really not that important.

But given the rules you quoted, adding minor version to SONAME sounds like a good idea regardless and would resolve my concern. Quickly going over the `/usr/lib` on my system, it seems at least openssl also puts minor version into SONAME, so there's some precedence.

**Comment by smuellerDD** [comment]
Am Donnerstag, 20. Mai 2021, 11:32:09 CEST schrieb Ondrej Mosnáček:

Hi Ondrej,

> I'd say it is a bit API-inompatible, too, since it can cause at least new
> compiler warnings with -Wconversion... but maybe that's really not that
> important.
> 
> But given the rules you quoted, adding minor version to SONAME sounds like a
> good idea regardless and would resolve my concern. Quickly going over the
> `/usr/lib` on my system, it seems at least openssl also puts minor version
> into SONAME, so there's some precedence.

I am pulling my hair out to convince libtool to take the minor version for the 
soname. But no success yet. If you have an idea how to tell this to libtool, I 
would be all ears. I tried playing around with -version-name, -version-info or 
even AC_INIT.


Ciao
Stephan

**Comment by simo5** [comment]
I am working on a symbol versioned fix as well, given currently older symbols are exposed with a changed signature.
That would allow us to avoid a soname bump.
The other option is, of course, reverting the change.

**Comment by smuellerDD** [comment]
Issue resolved as suggested in merge request #117.

Thanks a lot for your support.
