### ISSUE TITLE
speed measurement for hardware accelerators

### ISSUE THREAD

**Issue by jluebbe** [smuellerDD/libkcapi#121]
Unless I'm missing something, the kcapi-speed tool has a fixed list of drivers that it can use. This means that unless a driver name is listed in https://github.com/smuellerDD/libkcapi/blob/master/speed-test/cryptoperf-hash.c#L114, it can't be tested, correct?

For example on a STM32MP1, I have:
```
grep stm32 /proc/crypto | sort -u    
driver       : stm32-cbc-aes
driver       : stm32-cbc-des
driver       : stm32-cbc-des3
driver       : stm32-ccm-aes
driver       : stm32-crc32
driver       : stm32-ctr-aes
driver       : stm32-ecb-aes
driver       : stm32-ecb-des
driver       : stm32-ecb-des3
driver       : stm32-gcm-aes
driver       : stm32-hmac-md5
driver       : stm32-hmac-sha1
driver       : stm32-hmac-sha224
driver       : stm32-hmac-sha256
driver       : stm32-md5
driver       : stm32-sha1
driver       : stm32-sha224
driver       : stm32-sha256
```

Should each accelerator's supported algorithms be added to that list (via PRs)? Or is there a way to detect all available algorithms automatically? Perhaps by parsing `/proc/crypto`?

**Comment by smuellerDD** [comment]
Am Dienstag, 3. August 2021, 09:44:59 CEST schrieb Jan Lübbe:

Hi Jan,

> Unless I'm missing something, the kcapi-speed tool has a fixed list of
> drivers that it can use. This means that unless a driver name is listed in
> https://github.com/smuellerDD/libkcapi/blob/master/speed-test/cryptoperf-ha
> sh.c#L114, it can't be tested, correct?

That is correct. I used it to compare the performance against user space 
crypto implementations.

The key issue is to identify the supported modes for additional algorithms. 
Therefore, the tool needs the information that is to be provided in the array 
with all the algorithms.
> 
> For example on a STM32MP1, I have:
> ```
> grep stm32 /proc/crypto | sort -u
> driver       : stm32-cbc-aes
> driver       : stm32-cbc-des
> driver       : stm32-cbc-des3
> driver       : stm32-ccm-aes
> driver       : stm32-crc32
> driver       : stm32-ctr-aes
> driver       : stm32-ecb-aes
> driver       : stm32-ecb-des
> driver       : stm32-ecb-des3
> driver       : stm32-gcm-aes
> driver       : stm32-hmac-md5
> driver       : stm32-hmac-sha1
> driver       : stm32-hmac-sha224
> driver       : stm32-hmac-sha256
> driver       : stm32-md5
> driver       : stm32-sha1
> driver       : stm32-sha224
> driver       : stm32-sha256
> ```
> 
> Should each accelerator's supported algorithms be added to that list (via
> PRs)?

For the moment, yes.

> Or is there a way to detect all available algorithms automatically?
> Perhaps by parsing `/proc/crypto`?

/proc/crypto only contains the algorithms that were allocated at least once. 
Thus, this file cannot serve as the exhaustive list.

This together with the considerations mentioned above that some additional 
information is needed for each algo, I am yet not sure how to fully automate 
everything. If you have suggestions or patches, I am all ears. :-)

Ciao
Stephan

Ciao
Stephan

**Comment by smuellerDD** [comment]
Patch for #135 applied. Closing
