### ISSUE TITLE
kcapi-enc and AEAD setkey issue

### ISSUE THREAD

**Issue by egorenar** [smuellerDD/libkcapi#122]
Hi,

i'm in doubt that `set_key` for AEAD is correctly implemented in **kcapi-enc**.
The kernel drivers use https://elixir.bootlin.com/linux/latest/source/include/crypto/authenc.h#L29 to extract AEAD auth and enc keys. Does that mean that `kcapi-enc` expects the user to build the correct key buffer including `struct rtattr` ?
Furthermore, `keybuf` of length 32 might be too small. Currently, i'm implementing a driver for a crypto HW and it requires at least 32 bytes of key material w/o `struct rtattr` which is expected as header by `crypto_authenc_extractkeys`.

I "fixed" `kcapi-enc` keybuf length and then built the key file as expected by `crypto_authenc_extractkeys`. And it seems to work now nicely with e.g. `authenc(hmac(sha1),cbc(aes))` AEAD mode implemented by the driver.

Regards
Alex

**Comment by smuellerDD** [comment]
Am Sonntag, 5. September 2021, 20:14:45 CEST schrieb Alexander Egorenkov:

Hi Alexander,

> Hi,
> 
> i'm in doubt that `set_key` for AEAD is correctly implemented in
> **kcapi-enc**. The kernel drivers use
> https://elixir.bootlin.com/linux/latest/source/include/crypto/authenc.h#L29
> to extract AEAD auth and enc keys. Does that mean that `kcapi-enc` expects
> the user to build the correct key buffer including `struct rtattr` ?

The authenc() algorithms are intended for IPSec. Surely they can be used for 
any other operation, but I am not sure what the goal would be considering that 
they are not really used outside of IPSec.

Yet, GCM or CCM are common algorithms that are commonly used.

GCM/CCM is usable with the tool as expected.

But yes, if you want to use authenc() with kcapi-enc, so far, the key must be 
formatted according to this structure.

> Furthermore, `keybuf` of length 32 might be too small. Currently, i'm
> implementing a driver for a crypto HW and it requires at least 32 bytes of
> key material w/o `struct rtattr` which is expected as header by
> `crypto_authenc_extractkeys`.

Feel free to send patches :-)
> 
> I "fixed" `kcapi-enc` keybuf length and then built the key file as expected
> by `crypto_authenc_extractkeys`. And it seems to work now nicely with e.g.
> `authenc(hmac(sha1),cbc(aes))` AEAD mode implemented by the driver.

I would be happy to integrate the patch.

Thanks
Stephan
> 
> Regards
> Alex


Ciao
Stephan

**Comment by smuellerDD** [comment]
Closing the issue as it is no bug. If you want to provide a patch covering the enhancement, please submit it. If you feel this is still a bug, please reopen and provide more details. Thanks.
