### ISSUE TITLE
 Potential leak of memory 

### ISSUE THREAD

**Issue by pavlinux** [smuellerDD/libkcapi#124]
```
# make scan

test/kcapi-main.c:216:2: warning: Potential leak of memory pointed to by 'buf'
        return 0;
        ^~~~~~~~
1 warning generated.
```

**Comment by smuellerDD** [comment]
Am Sonntag, dem 19.09.2021 um 03:03 -0700 schrieb Pavel Vasilyev:
> Closed #124.
> 

Agreed, I am not seeing where there would be a leak.

Thanks
Stephan

**Comment by pavlinux** [comment]
>  I am not seeing where there would be a leak.

https://github.com/smuellerDD/libkcapi/blob/356bbd748b068c4ca047c117e0bb07f6672968ce/test/kcapi-main.c#L3880

**Comment by pavlinux** [comment]
>  I am not seeing where there would be a leak.

https://github.com/smuellerDD/libkcapi/blob/356bbd748b068c4ca047c117e0bb07f6672968ce/test/kcapi-main.c#L3880
