### ISSUE TITLE
FTBFS on hppa - undefined symbols

### ISSUE THREAD

**Issue by malaterre** [smuellerDD/libkcapi#133]
Let see if I can get input from you guys on the following issue we have within Debian on hppa arch.

It turns out that the symbol black magic introduced in 1.3.1 makes the compilation of libkcapi fails on hppa arch:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003088

It looks like the symbols that are messing the builds are the ones duplicated from one version to another, for example: `kcapi_cipher_stream_init_enc` which is either:

```
kcapi_cipher_stream_init_enc@LIBKCAPI_0.12.0
kcapi_cipher_stream_init_enc@LIBKCAPI_1.3.1
```

**Comment by malaterre** [comment]
In particular compare the output of:

```
malat@panama ~/libkcapi-1.3.0 % nm -D ./.libs/libkcapi.so | grep kcapi_aead_stream_init_enc
00008688 T kcapi_aead_stream_init_enc@@LIBKCAPI_0.12.0
```

vs:

```
malat@panama ~/libkcapi-1.3.1 % nm -D ./.libs/libkcapi.so | grep kcapi_aead_stream_init_enc
         U kcapi_aead_stream_init_enc
```

**Comment by malaterre** [comment]
@simo5 any suggestions ?

**Comment by simo5** [comment]
sounds like hppa tooling is failing to understand how to deal with symbol vesioning correctly?
what compiler version is this, what linker?

**Comment by malaterre** [comment]
Staring at the log file:

* https://buildd.debian.org/status/fetch.php?pkg=libkcapi&arch=hppa&ver=1.3.1-1&stamp=1641233787&raw=0

I see:

`gcc-11_11.2.0-13`

and

`binutils-common_2.37-10` `binutils-hppa-linux-gnu_2.37-10 `

**Comment by malaterre** [comment]
I'll cherry-pick also 3e9a1494dd2401094675fb54b1013022bd7933b8 just in case and see how it goes on debian buildds machines.

**Comment by simo5** [comment]
Sounds like you should pull in some gcc expert to see if there are bugs that are specific to hppa. I haven't touched that arch in more than a decade, and I am not aware of differences with it that we need to account for.
Are we sure there are no debian patches that are breaking this?

**Comment by smuellerDD** [comment]
Am Freitag, 28. Januar 2022, 16:49:40 CET schrieb Mathieu Malaterre:

Hi Mathieu,

> If I cherry-pick commit 71d80bcffca26373149121e026d612146b4695d5, the build
> on hppa succeeds...

If you say that these patches in the master branch are fixing your issue, then 
I will see to release a new version so that we have an official version with 
the fixes.

I am a bit behind with the review of a few patches. Once I completed that, I 
would certainly cut a new release.

Ciao
Stephan

**Comment by simo5** [comment]
> If I cherry-pick commit [71d80bc](https://github.com/smuellerDD/libkcapi/commit/71d80bcffca26373149121e026d612146b4695d5), the build on hppa succeeds...

Ah sorry, did not realize these commits hadn't made a release yet, as we applied them downstream in Fedora as well.

**Comment by malaterre** [comment]
@simo5 the description of 71d80bc refer to the use of FLTO which is not my case on hppa (or at least I could not see an explicit reference to flto in the build log)

**Comment by malaterre** [comment]
FYI, I forwarded the issue upstream:

* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104363

I believe this is safe now to close this issue. Thanks all.
