### ISSUE TITLE
Compile error with musl libc

### ISSUE THREAD

**Issue by z3ntu** [smuellerDD/libkcapi#136]
Observed on armv7, aarch64 & x86_64 (although the error seems to change slightly on 32-bit arches)
```
lib/kcapi-kernel-if.c: In function '_kcapi_common_send_meta':
lib/kcapi-kernel-if.c:212:26: error: unsigned conversion from 'long int' to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-Werror=sign-conversion]
  212 |                 header = CMSG_NXTHDR(&msg, header);
      |                          ^~~~~~~~~~~
lib/kcapi-kernel-if.c:212:26: error: unsigned conversion from 'long int' to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-Werror=sign-conversion]
lib/kcapi-kernel-if.c:228:26: error: unsigned conversion from 'long int' to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-Werror=sign-conversion]
  228 |                 header = CMSG_NXTHDR(&msg, header);
      |                          ^~~~~~~~~~~
lib/kcapi-kernel-if.c:228:26: error: unsigned conversion from 'long int' to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-Werror=sign-conversion]
cc1: all warnings being treated as errors
```

**Comment by e06620227** [comment]
expand the macro CMSG_NXTHDR  https://git.musl-libc.org/cgit/musl/tree/include/sys/socket.h#n355
we can see macro __CMSG_LEN(cmsg) need to replace  https://git.musl-libc.org/cgit/musl/tree/include/sys/socket.h#n350
a type conversion exists here

Also mentioned here
https://www.openwall.com/lists/musl/2022/02/16/7

**Comment by z3ntu** [comment]
@e06620227 So you're saying this needs to be fixed in musl itself or what?

**Comment by smuellerDD** [comment]
Am Freitag, 11. März 2022, 17:14:31 CET schrieb Luca Weiss:

Hi Luca,

> ```
> lib/kcapi-kernel-if.c: In function '_kcapi_common_send_meta':
> lib/kcapi-kernel-if.c:212:26: error: unsigned conversion from 'long int' to
> 'long unsigned int' changes value from '-8' to '18446744073709551608'
> [-Werror=sign-conversion] 212 |                 header = CMSG_NXTHDR(&msg,
> header);
> 
>       |                          ^~~~~~~~~~~
> 
> lib/kcapi-kernel-if.c:212:26: error: unsigned conversion from 'long int' to
> 'long unsigned int' changes value from '-8' to '18446744073709551608'
> [-Werror=sign-conversion] lib/kcapi-kernel-if.c:228:26: error: unsigned
> conversion from 'long int' to 'long unsigned int' changes value from '-8'
> to '18446744073709551608' [-Werror=sign-conversion] 228 |                
> header = CMSG_NXTHDR(&msg, header);
> 
>       |                          ^~~~~~~~~~~
> 
> lib/kcapi-kernel-if.c:228:26: error: unsigned conversion from 'long int' to
> 'long unsigned int' changes value from '-8' to '18446744073709551608'
> [-Werror=sign-conversion] cc1: all warnings being treated as errors
> ```

Thanks for the report - this is a type casting issue that is caught with the 
strict compilation rules.

The issue seems to be with the C library you are using. struct cmsghdr *header 
and CMSG_NXTHDR comes from sys/socket.h. Thus, I am not sure this is 
libkcapi's fault.

Yet, let us try to find the issue: which C library are you using?

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Sonntag, 27. März 2022, 16:06:37 CEST schrieb Luca Weiss:

Hi Luca,

> @e06620227 So you're saying this needs to be fixed in musl itself or what?

Sorry for the delay. 

Are you saying that the patch [1] is not sufficient?

[1] https://github.com/smuellerDD/libkcapi/commit/
12f19b9a1dd308117f83e8cb33e28e3c040710a0

Ciao
Stephan

**Comment by z3ntu** [comment]
Doesn't look like it, that commit is apparently in v1.4.0 and in the build logs of that version the warning (with removed Werror) is still present
```
lib/kcapi-kernel-if.c: In function '_kcapi_common_send_meta':
lib/kcapi-kernel-if.c:212:26: warning: unsigned conversion from 'long int' to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-Wsign-conversion]
  212 |                 header = CMSG_NXTHDR(&msg, header);
      |                          ^~~~~~~~~~~
lib/kcapi-kernel-if.c:212:26: warning: unsigned conversion from 'long int' to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-Wsign-conversion]
lib/kcapi-kernel-if.c:228:26: warning: unsigned conversion from 'long int' to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-Wsign-conversion]
  228 |                 header = CMSG_NXTHDR(&msg, header);
      |                          ^~~~~~~~~~~
lib/kcapi-kernel-if.c:228:26: warning: unsigned conversion from 'long int' to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-Wsign-conversion]
```
https://build.alpinelinux.org/buildlogs/build-edge-x86_64/main/libkcapi/libkcapi-1.4.0-r0.log

**Comment by smuellerDD** [comment]
Am Dienstag, dem 11.10.2022 um 02:41 -0700 schrieb Luca Weiss:
> Doesn't look like it, that commit is apparently in v1.4.0 and in the build
> logs of that version the warning (with removed Werror) is still present
> ```
> lib/kcapi-kernel-if.c: In function '_kcapi_common_send_meta':
> lib/kcapi-kernel-if.c:212:26: warning: unsigned conversion from 'long int'
> to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-
> Wsign-conversion]
>   212 |                 header = CMSG_NXTHDR(&msg, header);
>       |                          ^~~~~~~~~~~
> lib/kcapi-kernel-if.c:212:26: warning: unsigned conversion from 'long int'
> to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-
> Wsign-conversion]
> lib/kcapi-kernel-if.c:228:26: warning: unsigned conversion from 'long int'
> to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-
> Wsign-conversion]
>   228 |                 header = CMSG_NXTHDR(&msg, header);
>       |                          ^~~~~~~~~~~
> lib/kcapi-kernel-if.c:228:26: warning: unsigned conversion from 'long int'
> to 'long unsigned int' changes value from '-8' to '18446744073709551608' [-
> Wsign-conversion]
> ```
> https://build.alpinelinux.org/buildlogs/build-edge-x86_64/main/libkcapi/libkcapi-1.4.0-r0.log
> 

I do not believe that is an issue of libkcapi. It just reports it because it
is compiled with -Wconversion and -Werror - both are options not commonly used
as otherwise you would not be able to compile OpenSSL and other challenging
software.

Anyhow, CMSG_NXTHDR processes msg and header, both are defined as:

struct cmsghdr *header = NULL;
struct msghdr msg;

Both data types are not defined in libkcapi, but in the libc you are using
just like CMSG_NXTHDR. I.e. the error is caused solely by implementations not
provided by libkcapi. Thus, I personally think that the issue is rather in the
libc implementation that is of use here.

Ciao
Stephan

**Comment by z3ntu** [comment]
@nekopsykose since you now maintain libkcapi in Alpine, do you maybe know more about this? Or just keep Werror disabled is as patched now?

**Comment by smuellerDD** [comment]
Am Dienstag, dem 11.10.2022 um 04:32 -0700 schrieb Luca Weiss:
> @nekopsykose since you now maintain libkcapi in Alpine, do you maybe know
> more about this? Or just keep Werror disabled is as patched now?

Just as a side note, it is not -Werror that causes the issue, it is -
Wconversion which flags any conversions from int to unsigned int and vice
versa.

Ciao
Stephan

**Comment by nekopsykose** [comment]
> @nekopsykose since you now maintain libkcapi in Alpine, do you maybe know more about this? Or just keep Werror disabled is as patched now?  

i don't really have any input- both the types and 'api' come from the libc itself, so i would assume there is something wrong there to use the cmsg macros on their own types and end up with an int conversion warning. but, if i had to guess, it is actually perfectly safe and can be ignored (really, just a guess). ask in musl irc if you want, but in general i always remove -Werror from everything :)

**Comment by z3ntu** [comment]
Fine from my side then.

**Comment by ffontaine** [comment]
We have the same build failure on buildroot with musl since bump to version 1.4.0. I would like to avoid carrying a non upstreamable patch that removes `-Werror` ... Would you accept a PR that allows the user to disable `-Werror` through a confugure option such as `--disable-werror`?

**Comment by smuellerDD** [comment]
Am Sonntag, 6. November 2022, 18:51:43 CET schrieb Fabrice Fontaine:

Hi Fabrice,

> We have the same build failure on buildroot with musl since bump to version
> 1.4.0. I would like to avoid carrying a non upstreamable patch that removes
> `-Werror` ... Would you accept a PR that allows the user to disable
> `-Werror` through a confugure option such as `--disable-werror`?

I would accept to remove -Werror if that truly helps.

My only concern is that there is an implicit type cast. A large number of 
OpenSSL's CVEs are based on implicit type casts where lengths are interpreted 
as signed.

Let me know if you truly think removing -Werror is the right course of action 
and I will remove it.

Ciao
Stephan

**Comment by ffontaine** [comment]
I think you should keep `-Werror` enabled by default. However, having an option to disable it in downstream projects such as buildroot would really be great.

**Comment by smuellerDD** [comment]
Am Montag, 7. November 2022, 08:55:18 CET schrieb Fabrice Fontaine:

Hi Fabrice,

> I think you should keep `-Werror` enabled by default. However, having an
> option to disable it in downstream projects such as buildroot would really
> be great.

Very good. Do you want to provide a patch?

Ciao
Stephan

**Comment by ffontaine** [comment]
Yes, I will provide it
