### ISSUE TITLE
Error messages pollute stderr, breaking various programs

### ISSUE THREAD

**Issue by Vogtinator** [smuellerDD/libkcapi#138]
If an application or library using libkcapi is run on a kernel which doesn't have a required feature enabled, like `AF_ALG`, libkcapi by default writes an error message to stderr. While the caller of libkcapi can deal with the error and continue despite that, it fails because the error message itself is not expected by the caller.

e.g. the libzip testsuite fails:

```
[   61s] 144/145 Test #144: zip64_stored_creation.test .......................***Failed   12.71 sec
[   61s] Unexpected error output:
[   61s] --- expected
[   61s] +++ got
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
[   61s] zip64_stored_creation -- FAIL: error output
```

I suggest to default to not print any messages by default, not even error messages, unless they're fatal and result in immediate program termination.

Allowing the library user to handle messages e.g. by registering a logging callback might be useful.

**Comment by smuellerDD** [comment]
Am Freitag, 6. Mai 2022, 09:57:11 CEST schrieb Fabian Vogt:

Hi Fabian,

> If an application or library using libkcapi is run on a kernel which doesn't
> have a required feature enabled, like `AF_ALG`, libkcapi by default writes
> an error message to stderr. While the caller of libkcapi can deal with the
> error and continue despite that, it fails because the error message itself
> is not expected by the caller.

Sorry for the delay.

How would you suggest to handle that case? Per default, the log level is 
KCAPI_LOG_ERR. During start time of your app, you could set it to 
KCAPI_LOG_NONE to not issue any logs.

IMHO the caller, i.e. your test suite, needs an update: it should stop using 
libkcapi if it cannot initialize the cipher handle.


> 
> e.g. the libzip testsuite fails:
> 
> ```
> [   61s] 144/145 Test #144: zip64_stored_creation.test
> .......................***Failed   12.71 sec [   61s] Unexpected error
> output:
> [   61s] --- expected
> [   61s] +++ got
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] +libkcapi - Error: AF_ALG: socket syscall failed (errno: -97)
> [   61s] zip64_stored_creation -- FAIL: error output
> ```
> 
> I suggest to default to not print any messages by default, not even error
> messages, unless they're fatal and result in immediate program termination.
> 
> Allowing the library user to handle messages e.g. by registering a logging
> callback might be useful.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Change applied. Thanks.
