### ISSUE TITLE
key size fixed at 32 bytes (need 52 for CAAM related "black" keys)

### ISSUE THREAD

**Issue by flobro30101** [smuellerDD/libkcapi#141]
I am using an NXP imx8mq processor and tried kcapi-enc to encrypt a file and kept hitting -EINVAL when the key was being set setsockopt(3, SOL_ALG, ALG_SET_KEY...). I am using the "tk(cbc(aes))" cipher.

This was because the keybuf was capped at 32 bytes where a black key needs 52 bytes. I upped my version of keybuf to 64 bytes and it worked perfectly.

I can live with my version as I don't know if anyone else would need this. 

I really do appreciate this library since I was studying the kernel user interface and realized how much more code was needed to handle large files. Thank all of you involved, it is much easier to do.

**Comment by flobro30101** [comment]
diff --git a/apps/kcapi-enc.c b/apps/kcapi-enc.c
index 1550f84..739242e 100644
--- a/apps/kcapi-enc.c
+++ b/apps/kcapi-enc.c
@@ -729,7 +729,7 @@ static int set_key(struct kcapi_handle *handle, struct
opt_data *opts)
 {
        uint8_t passwdbuf[128] __aligned(KCAPI_APP_ALIGN);
        uint32_t passwdlen = 0;
-       uint8_t keybuf[32] __aligned(KCAPI_APP_ALIGN);
+       uint8_t keybuf[64] __aligned(KCAPI_APP_ALIGN);
        uint32_t keybuflen = 0;
        int have_key = 0;
        const uint8_t *passwdptr = NULL;
Thanks

Floyd Brown
678.453.6069

**Comment by smuellerDD** [comment]
Applied, thanks.
