### ISSUE TITLE
Kernel API patches Status

### ISSUE THREAD

**Issue by duplexsystem** [smuellerDD/libkcapi#149]
Will the asym or kpp patches ever be mainlined? Are these patches still updated to newer kernel versions when breakage occurs? I would like for these APIs to work in order to access hardware crypto for these algorithms more easily. Also is there any possibility of a compression/deflate api?

Thanks!

**Comment by smuellerDD** [comment]
Am Mittwoch, 11. Januar 2023, 22:26:01 CET schrieb Zoë Gidiere:

Hi Zoë,

> Will the asym or kpp patches ever be mainlined? Are these patches still
> updated to newer kernel versions when breakage occurs? I would like for
> these APIs to work in order to access hardware crypto for these algorithms
> more easily. Also is there any possibility of a compression/deflate api?

These patches are not applying to current kernel versions. But they can be 
updated to make them fit.

Yet, so far upstream has not accepted them as it was not considered 
worthwhile.

Please ask upstream that you would need that and inquire whether the patch 
series could be considered (after dusting them up).
> 
> Thanks!


Ciao
Stephan

**Comment by duplexsystem** [comment]
Hey Stephan,

> These patches are not applying to current kernel versions. But they can be
updated to make them fit.

Alright thanks for the heads up!

> Yet, so far upstream has not accepted them as it was not considered
worthwhile.

Do you have an archive of this? I can't seem to find it.

> Please ask upstream that you would need that and inquire whether the patch
series could be considered (after dusting them up).

Should I fix them up, then submit them and ask or ask and then fix them up if they say yes?

Thanks!

**Comment by smuellerDD** [comment]
Am Donnerstag, 12. Januar 2023, 21:25:00 CET schrieb Zoë Gidiere:

Hi Zoë,

> Hey Stephan,
> 
> > These patches are not applying to current kernel versions. But they can be
> 
> updated to make them fit.
> 
> Alright thanks for the heads up!
> 
> > Yet, so far upstream has not accepted them as it was not considered
> 
> worthwhile.
> 
> Do you have an archive of this? I can't seem to find it.

This was long time ago. I think in 2018 or 2019 when I submitted the patches 
for inclusion to the linux-crypto mailing list.
> 
> > Please ask upstream that you would need that and inquire whether the patch
> 
> series could be considered (after dusting them up).
> 
> Should I fix them up, then submit them and ask or ask and then fix them up
> if they say yes?

If you want, feel free to dust them up :-)
> 
> Thanks!


Ciao
Stephan
