### ISSUE TITLE
Specify key length for kcapi-enc

### ISSUE THREAD

**Issue by ziyao233** [smuellerDD/libkcapi#150]
This issue is similar to #141 .

When working with `SM4` algorithm,  `setsockopt()` fails with errno `-EINVAL`. This is because `SM4` supports 16-byte keys only but a 32-byte key is used by `kcapi-enc`.

An optional solution is to add an option to `kcapi-enc` to specify key length, imho.

**Comment by smuellerDD** [comment]
Applied with few modifications.
