### ISSUE TITLE
How to configure the cross compiler toolchain？

### ISSUE THREAD

**Issue by bqiu728** [smuellerDD/libkcapi#154]
Hi,

It seems that when I use this command to configure ：
`./configure --prefix=/usr/ --enable-kcapi-test`
it will use gcc as the default cross compiler. And I‘ve tried to find is there any option in `./configure` to change it. I got non.
So how can I change the  cross compiler toolchain ?

Thanks

**Comment by smuellerDD** [comment]
Am Montag, 3. April 2023, 14:07:50 CEST schrieb bqiu728:

Hi bqiu728,

> Hi,
> 
> It seems that when I use this command to configure ：
> `./configure --prefix=/usr/ --enable-kcapi-test`
> it will use gcc as the default cross compiler. And I‘ve tried to find is
> there any option in `./configure` to change it. I got non. So how can I
> change the  cross compiler toolchain ?
> 
> Thanks

https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Hosts-and-Cross_002dCompilation.html

Ciao
Stephan
