### ISSUE TITLE
Where does the function `kcapi_md_final`  implement ?

### ISSUE THREAD

**Issue by bqiu728** [smuellerDD/libkcapi#155]
Hi,

Could you pls help me to tell me that where does the function `kcapi_md_final`  implement. 
I've searched the whole project, but could not find it 

thanks

**Comment by smuellerDD** [comment]
Am Donnerstag, 6. April 2023, 17:14:07 CEST schrieb bqiu728:

Hi bqiu728,

> Hi,
> 
> Could you pls help me to tell me that where does the function
> `kcapi_md_final`  implement. I've searched the whole project, but could not
> find it
> 
> thanks

https://github.com/smuellerDD/libkcapi/blob/master/lib/kcapi-md.c#L75 from the 
API call in https://github.com/smuellerDD/libkcapi/blob/master/lib/kcapi-md.c#L101.


Ciao
Stephan
