### ISSUE TITLE
Is `kcapi_handle` thread-safe?

### ISSUE THREAD

**Issue by wiktor-k** [smuellerDD/libkcapi#158]
Hello,

I'm working on improving [Rust bindings for kcapi](https://github.com/puru1761/kcapi) and I'm pondering whether `kcapi_handle`s in general are safe to use from multiple threads?

I've been reading `kcapi.h` and there are quite a lot of mentions of "The parallel execution can be performed in the same or different process threads." ([source](https://github.com/smuellerDD/libkcapi/blob/master/lib/kcapi.h#L86)) and my local tests indicate that indeed multi-threaded access works correctly (I've used hashing API).

Thank you for your insight and time! :wave:

**Comment by smuellerDD** [comment]
Am Dienstag, 20. Juni 2023, 14:08:44 CEST schrieb Wiktor Kwapisiewicz:

Hi Wiktor,

sorry for the delay.

> Hello,
> 
> I'm working on improving [Rust bindings for
> kcapi](https://github.com/puru1761/kcapi) and I'm pondering whether
> `kcapi_handle`s in general are safe to use from multiple threads?

The library is reentrant, but the handles are not thread-safe. I.e. using the 
handle by multiple threads requires a lock. This is due to the fact that the 
handle contains state information which is updated with non-atomic operations. 
Thus, when you have parallel threads using the same handle, you can get 
inconsistent handles.

Yet, you have multiple handles (e.g. one per thread) then you do not need a 
lock. I.e. the library and the AF_ALG iterface is fully thread-safe and you 
can have multiple parallel requests (with multiple parallel handles).
> 
> I've been reading `kcapi.h` and there are quite a lot of mentions of "The
> parallel execution can be performed in the same or different process
> threads."
> ([source](https://github.com/smuellerDD/libkcapi/blob/master/lib/kcapi.h#L8
> 6)) and my local tests indicate that indeed multi-threaded access works
> correctly (I've used hashing API).
> 
> Thank you for your insight and time! :wave:


Ciao
Stephan

**Comment by wiktor-k** [comment]
> sorry for the delay.

No problem at all!

> The library is reentrant, but the handles are not thread-safe. I.e. using the
handle by multiple threads requires a lock. This is due to the fact that the
handle contains state information which is updated with non-atomic operations.
Thus, when you have parallel threads using the same handle, you can get
inconsistent handles.

That clears a lot of my questions. One remains: can I move a handle from one thread to another? A hypothetical use case: I update the hash (`kcapi_md_update`) in one thread and then move that handle to another thread for hash finalization (`kcapi_md_final`). The handle would be used only by a *single* thread at a time but potentially by a different one throughout its lifetime. (I'm not sure if there are any thread local state in there).

> Yet, you have multiple handles (e.g. one per thread) then you do not need a
lock. I.e. the library and the AF_ALG iterface is fully thread-safe and you
can have multiple parallel requests (with multiple parallel handles).

That's good to hear!

Thank you for help and this great library.

**Comment by smuellerDD** [comment]
Am Donnerstag, 22. Juni 2023, 10:17:49 CEST schrieb Wiktor Kwapisiewicz:

Hi Wiktor,

> > sorry for the delay.
> 
> No problem at all!
> 
> > The library is reentrant, but the handles are not thread-safe. I.e. using
> > the
> handle by multiple threads requires a lock. This is due to the fact that the
> handle contains state information which is updated with non-atomic
> operations. Thus, when you have parallel threads using the same handle, you
> can get inconsistent handles.
> 
> That clears a lot of my questions. One remains: can I move a handle from one
> thread to another? 

Yes, always. Each API call may update the handle. But after the API call 
completes, the handle is per definition always in a consistent state. In 
addition, there is no state anywhere else that a handle relies on. Thus, a 
handle is fully self-contained.

> A hypothetical use case: I update the hash
> (`kcapi_md_update`) in one thread and then move that handle to another
> thread for hash finalization (`kcapi_md_final`). The handle would be used
> only by a *single* thread at a time but potentially by a different one
> throughout its lifetime. (I'm not sure if there are any thread local state
> in there).

This is perfectly ok.

> > Yet, you have multiple handles (e.g. one per thread) then you do not need
> > a
> 
> lock. I.e. the library and the AF_ALG iterface is fully thread-safe and you
> can have multiple parallel requests (with multiple parallel handles).
> 
> That's good to hear!
> 
> Thank you for help and this great library.

Thank you :-)


Ciao
Stephan

**Comment by wiktor-k** [comment]
As everything concern has been resolved to completion I'm closing this issue.

Once again: your work is greatly appreciated and... have a nice day! 👋
