### ISSUE TITLE
Does LibkcAPI support CFB1/CFB8?

### ISSUE THREAD

**Issue by sikkamukul** [smuellerDD/libkcapi#160]
Hi Stephan,
I was trying to write libkcapi backend code in ACVP(https://github.com/smuellerDD/acvpparser) but couldn't find a way to add support for CFB8 and CFB1.
Thanks,
Mukul Sikka

**Comment by smuellerDD** [comment]
Am Dienstag, 27. Juni 2023, 11:22:11 CEST schrieb sikkamukul:

Hi sikkamukul,

> Hi Stephan,
> I was trying to write libkcapi backend code in
> ACVP(https://github.com/smuellerDD/acvpparser) but couldn't find a way to
> add support for CFB8 and CFB1. can help me to figure it out.
> Thanks,
> Mukul Sikka

How do you conclude that CFB8 and CFB1 are supported? When I look into the 
code, I only see CFB128/64 being supported.

Ciao
Stephan

**Comment by sikkamukul** [comment]
Thanks for your quick response
I am not a kernel expert so wasn't sure if they are supported.
