### ISSUE TITLE
vmsplice() with SPLICE_F_GIFT should not be used on memory allocated from the heap (ie. calloc)

### ISSUE THREAD

**Issue by dhowells** [smuellerDD/libkcapi#162]
Passing SPLICE_F_GIFT to vmsplice() allows the kernel to excise the entire page(s) containing the data from the calling process's address space (typically when page is spliced out of the pipe with SPLICE_F_MOVE).  If this page is in the heap, this could wreck malloc's metadata there.

SPLICE_F_GIFT does not gain you anything if you're just passing the data to AF_ALG.  The pages from the userspace process are spliced into the pipe anyway, even without SPLICE_F_GIFT.  At present, it merely sets a flag that the other end can take note of.

To quote the vmsplice(2) manual page:

       SPLICE_F_GIFT
              The user pages are a gift to the kernel.   The  application  may
              not  modify  this  memory ever, otherwise the page cache and on-
              disk data may differ.  Gifting pages to the kernel means that  a
              subsequent  splice(2)  SPLICE_F_MOVE  can  successfully **move** the
              pages;  if  this  flag  is  not  specified,  then  a  subsequent
              splice(2)  SPLICE_F_MOVE must copy the pages.  Data must also be
              properly page aligned, both in memory and length.

**Comment by smuellerDD** [comment]
Am Donnerstag, 6. Juli 2023, 08:06:06 CEST schrieb dhowells:

Hi David,

> Passing SPLICE_F_GIFT to vmsplice() allows the kernel to excise the entire
> page(s) containing the data from the calling process's address space
> (typically when page is spliced out of the pipe with SPLICE_F_MOVE).  If
> this page is in the heap, this could wreck malloc's metadata there.
> 
> SPLICE_F_GIFT does not gain you anything if you're just passing the data to
> AF_ALG.  The pages from the userspace process are spliced into the pipe
> anyway, even without SPLICE_F_GIFT.  At present, it merely sets a flag that
> the other end can take note of.
> 
> To quote the vmsplice(2) manual page:
> 
>        SPLICE_F_GIFT
>               The user pages are a gift to the kernel.   The  application 
> may not  modify  this  memory ever, otherwise the page cache and on- disk
> data may differ.  Gifting pages to the kernel means that  a subsequent 
> splice(2)  SPLICE_F_MOVE  can  successfully **move** the pages;  if  this 
> flag  is  not  specified,  then  a  subsequent splice(2)  SPLICE_F_MOVE
> must copy the pages.  Data must also be properly page aligned, both in
> memory and length.

Thank you very much, I will see to remove it.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Patch applied.
