### ISSUE TITLE
Can't get `kcapi_akcipher_init` with `rsa` working locally

### ISSUE THREAD

**Issue by wiktor-k** [smuellerDD/libkcapi#164]
Hi,

I'd like to use asymmetric ciphers (ie. `rsa`) but for some reason the algorithm is not found (-2; `ENOENT`).

It seems the algorithm is enabled:

```
$ grep -A 5 rsa /proc/crypto 
name         : pkcs1pad(rsa,sha256)
driver       : pkcs1pad(rsa-generic,sha256)
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
--
name         : rsa
driver       : rsa-generic
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
```

But when I invoke one of the test commands [I found in the source](https://github.com/smuellerDD/libkcapi/blob/master/test/kcapi-main.c#L4060) I get the -2 error (ENOINT) (The same happens with `pkcs1pad(rsa-generic,sha256)`):

```
$ ./kcapi -x 4 -o 0 -c "rsa" -r 3082010902820100DB101AC2A3F1DCFF136BED44DFF0026D13C788DA706B54F1E827DCC30F996AFAC667FF1D1E3C1DC1B55F6CC0B2073A6D41E42599ACFCD20F02D3D154061A5177BDB6BFEAA75C06A95D698445D7F505BA47F01BD72B24ECCB9B1B108D81A0BEB18C33E436B843EB192A818DDE810A9948B6F6BCCD49343A8F2694E328821A7C8F599F45E85D1A4576045605A1D01B8C776DAF53FA71E267E09AFE03A985D2C9AABA2ABCF4A008F51398135DF0D933342A61C38955F0AE1A9C22EE19058D32FEEC9C84BAB7F96C3A4F07FC45EB12E57BFD55E62969D1C2E8B97859F67910C64EEB6A5EB99AC7C45B63DAA33F5E927A815ED6B0E2628F7426C20CD39A1747E68EAB0203010001 -p 54859b342c49ea2a
libkcapi - Error: AF_ALG: bind failed (errno: -2)
Allocation of rsa cipher failed
Failed to invoke testing
```

I'm using fairly recent kernel:

```
$ uname -a
Linux radon 6.4.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 01 Jul 2023 16:17:21 +0000 x86_64 GNU/Linux
```

Which [should have appropriate modules enabled](https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/blob/main/config#L10631). I've checked the [kernel patches directory](https://github.com/smuellerDD/libkcapi/tree/master/kernel-patches/) but nothing seemed to be relevant. I've looked at modules in `/usr/lib/modules/$(uname -r)/kernel/crypto/` but nothing regarding `rsa` sadly.

I used the following configure, which I found in the CI script:

```
./configure \
--enable-kcapi-hasher \
--enable-kcapi-test  \
--enable-kcapi-rngapp \
--enable-kcapi-encapp \
--enable-kcapi-dgstapp \
--enable-lib-asym \
--enable-lib-kpp \
--prefix=/tmp
```

Thanks for your time and help! :wave:

**Comment by wiktor-k** [comment]
:thinking: I've talked with @puru1761 and he updated me that the kernel patches for asym are still needed even with recent kernels... That's unfortunate.

Is there anything I could do to help getting them upstreamed?

(Context: I'm working on [adding kernel crypto backend to Sequoia PGP](https://gitlab.com/sequoia-pgp/sequoia/-/issues/1030) and having asymmetric crypto is definitely a must have :sweat_smile:)

**Comment by smuellerDD** [comment]
Am Dienstag, 11. Juli 2023, 10:41:03 CEST schrieb Wiktor Kwapisiewicz:

Hi Wiktor,

> :thinking: I've talked with @puru1761 and he updated me that the kernel
> :patches for asym are still needed even with recent kernels... That's
> :unfortunate.

Correct.

> Is there anything I could do to help getting them upstreamed?

Raise your voice upstream that you want / need them.
> 
> (Context: I'm working on [adding kernel crypto backend to Sequoia
> PGP](https://gitlab.com/sequoia-pgp/sequoia/-/issues/1030) and having
> asymmetric crypto is definitely a must have :sweat_smile:)

I can understand that. However, when I tried to push them, I got vetoed 
because it was considered that it is not needed.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, 13. Juli 2023, 10:24:36 CEST schrieb Wiktor Kwapisiewicz:

Hi Wiktor,

> Okay, great to have you confirming this.
> 
> I actually started working on it after a kernel developer asked about it on
> our mailing lists:
> ***@***.***/t
> hread/ZU64CWYZ26OH5TH6PR3BBLDYDDZ6COLH/
> > Another point would be to avoid external dependencies, like a crypto
> 
> library, and to use the kernel Crypto API instead (through
> socket(AF_ALG) in user space). Not the highest priority (as it would
> require to rewrite some parts of your library), but nice to have.
> 
> I will ask that person for their feedback and maybe we can move things
> forward here.
> 
> Thanks and have a nice day! :wave:

Sweet - keep me informed, please, if you make progress in convincing linux-
crypto mailing list of inserting AF_ALG for akcipher.

Ciao
Stephan

**Comment by wiktor-k** [comment]
Definitely will do :+1: 

As I wrote in my recent e-mail to the person asking for Kernel Crypto: https://lists.sequoia-pgp.org/hyperkitty/list/devel@lists.sequoia-pgp.org/message/VNCIBG6AOUPP4ZQ65KPI3LEXLEROFLGO/ I believe we've got a strong case here but first I'd like that person to get in touch with kernel people since, well, they already work on it and, to be honest, I never did that :blush: 

I'd be cool to see this feature implemented throughout the entire stack. Fingers crossed! :)

**Comment by wiktor-k** [comment]
Okay. This sadly didn't go exactly as planned :sweat_smile: 

Since we've got an answer on the mailing list I think it's safe to close this ticket as "not implemented".

For the record I've described the situation in our [tracking ticket](https://gitlab.com/sequoia-pgp/sequoia/-/issues/1030#note_1507831830).

Thanks for help, folks! :wave:
