### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [smuellerDD/libkcapi#17]
I would like to point out that identifiers like “[`_KCAPI_H`](https://github.com/smuellerDD/libkcapi/blob/b3b995a87e9c3707d84a278fd2b37347d53fbcf5/lib/kcapi.h#L20 "Update candidate")” and “[`__CRYPTO_MSG_MAX`](https://github.com/smuellerDD/libkcapi/blob/c86273792317342ab4876980593af760ef09ffe6/lib/cryptouser.h#L21 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by smuellerDD** [comment]
Changed in kcapi.h, internal.h and app-internal.h.

Yet, I am not going to touch cryptouser.h as this a header file coming from the kernel.

**Comment by smuellerDD** [comment]
Closing

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/smuellerDD/libkcapi/commit/a9e1c1f49fb96d3b17f42b2d362327e78afc293c "rename header guards").

I would appreciate if these identifiers will not only become [standard compliant](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") but [also safe for reuse](https://github.com/smuellerDD/libkcapi/issues/18 "Make include guards unique").
