### ISSUE TITLE
speed-tests: Bench of Asymmetric Cryptographic Algorithms

### ISSUE THREAD

**Issue by armfazh** [smuellerDD/libkcapi#172]
speed-test does not support asymmetric algorithms, such as signing and verifying.

**Comment by smuellerDD** [comment]
Am Mittwoch, 6. September 2023, 04:21:08 CEST schrieb Armando Faz:

Hi Armando,

> speed-test does not support asymmetric algorithms, such as signing and
> verifying.

There is no kernel interface to access asymmetric algorithms.

Ciao
Stephan

**Comment by armfazh** [comment]
(out of curiosity, also I'm not familiar with kernel devel) are there any plans to enable asymmetric crypto interfaces?

**Comment by smuellerDD** [comment]
Am Mittwoch, 6. September 2023, 18:50:37 CEST schrieb Armando Faz:

Hi Armando,

> (out of curiosity, also I'm not familiar with kernel devel) are there any
> plans to enable asymmetric crypto interfaces?

I got show down with adding that interface some years ago. Not too long ago, 
the question was raised again and shot down.

Ciao
Stephan
