### ISSUE TITLE
1.4.0: sha*hmac binaries has been removed? 🤔

### ISSUE THREAD

**Issue by kloczek** [smuellerDD/libkcapi#175]
I just started upgrade of my libkcapi rpm spec file to from 1.3.1 to 1.4.0 (by reuse old build procedure and change only version in that file) and suddenly found that after build and install there is no sha*hmac binaries.
I don't see any comments about that in CHANGES.md file.
Some other binaries now can provide the same functionality? 🤔

**Comment by smuellerDD** [comment]
Am Freitag, 20. Oktober 2023, 15:43:10 CEST schrieb Tomasz Kłoczko:

Hi Tomasz,

> I just started upgrade of my libkcapi rpm spec file to 1.4.0 (by reuse old
> build procedure and change only version in that file) and suddenly found
> that after build and install there is no sha*hmac binaries. I don't see any
> comments about that in CHANGES.md files.
> Some other binaries now can provide the same functionality? 🤔

If you use the git head, they have been moved to the libexec directory to 
avoid clashes with other identically named binaries from other packages.

Ciao
Stephan

**Comment by kloczek** [comment]
> If you use the git head, they have been moved to the libexec directory to
avoid clashes with other identically named binaries from other packages.

Yes in this case I've used additionally patches generate from commits above 1.4.0 tag.
In case distribution on which I;m working there is no such bin directory clashes.
If I'll move back everything to bindir is it will cause any issues caused by hardcoded somewhere libexcec directory?

**Comment by smuellerDD** [comment]
Am Freitag, 20. Oktober 2023, 15:59:54 CEST schrieb Tomasz Kłoczko:

Hi Tomasz,

> > If you use the git head, they have been moved to the libexec directory to
> 
> avoid clashes with other identically named binaries from other packages.
> 
> Yes in this case I've used additionally patches generate from commits above
> 1.4.0 tag. In case distribution on which I;m working there is no such bin
> directory clashes. If I'll move back everything to bindir is it will cause
> any issues caused by hardcoded somewhere libexcec directory?

There should be no issues when moving things around. Though, hardlinks are 
replaced by symlinks in the current head. But still, even that has no real 
implications to you if you move them around.

The basic idea, however, is instead of moving things around, you create a 
symlink from /bin or /usr/bin to the libexec binaries.


Ciao
Stephan

**Comment by kloczek** [comment]
Thank you 😄 
Nevertheless I think that some note about that should be dropped in CHANGES.md.
If may I ask for yet another unrelated question ..
Is it possible to embed somehow executables hmac signature in elf section instead keeping it in separated file?
I'm not asking for full description. If it some documentation about that pleas just drop URL.

Closing and one more time thank you very much for your time👍

**Comment by smuellerDD** [comment]
Am Freitag, 20. Oktober 2023, 16:18:53 CEST schrieb Tomasz Kłoczko:

Hi Tomasz,

> Thank you 😄
> Nevertheless I think that some note about that should be dropped in
> CHANGES.md.

Thank you, very good point. Done

> If may I ask for yet another unrelated question ..
> Is it possible to embed somehow executables hmac signature in elf section
> instead keeping it in separated file? I'm not asking for full description.
> If it some documentation about that pleas just drop URL.

Yes, that is quite possible. Have a look how OpenSSL FIPS 2.0.x did it when 
creating the fipscanister.o object.
> 
> Closing and one more time thank you very much for your time👍

Thanks :-)

Ciao
Stephan

**Comment by kloczek** [comment]
> Yes, that is quite possible. Have a look how OpenSSL FIPS 2.0.x did it when
creating the fipscanister.o object.

When I've started working on my distro initially inheriting build procedures from Fedora.
I just found that in openssl.spec is perfect example of use that using `rodata1` elf section
```spec
# Add generation of HMAC checksum of the final stripped library
# We manually copy standard definition of __spec_install_post
# and add hmac calculation/embedding to fips.so
%define __spec_install_post \
        %{?__debug_package:%{__debug_install_post}} \
        %{__arch_install_post} \
        %{__os_install_post} \
        LD_LIBRARY_PATH=. apps/openssl dgst -binary -sha256 -mac HMAC -macopt hexkey:f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813 < %{buildroot}%{_libdir}/ossl-modules/f
ips.so > %{buildroot}%{_libdir}/ossl-modules/fips.so.hmac \
        objcopy --update-section .rodata1=%{buildroot}%{_libdir}/ossl-modules/fips.so.hmac %{buildroot}%{_libdir}/ossl-modules/fips.so %{buildroot}%{_libdir}/ossl-modules/fips.so.mac \
        %__mv %{buildroot}%{_libdir}/ossl-modules/fips.so.mac %{buildroot}%{_libdir}/ossl-modules/fips.so \
        %__rm %{buildroot}%{_libdir}/ossl-modules/fips.so.hmac \
%{nil}
```

FYI actually looks like easiest way to move back additional symlinks without patching is by use on install `make install DESTDIR=</install_prefix> pkglibexecdir=/usr/bin` .

PS. To be honest I'm not familiar with use signed binaries.
(I don't want waste your time ..)
Can you point on some descent documentation about how to use whole Linux based system with only signed binaries using FIPS? 🤔  (examples of signing looks like I've already have and what is only missing is what needs to be changed in whole system/kernel and/or ls.so (probably? 🤔) side to always force verify FIPS signatures on execution or loading libraries and other DSOs)
Or .. at least for what king of keywords I should be looking for searching using google? 🤔

Again .. thank you very much for the hint with openssl FIPS👍 😋

**Comment by smuellerDD** [comment]
Am Freitag, 20. Oktober 2023, 17:06:23 CEST schrieb Tomasz Kłoczko:

Hi Tomasz,

> > Yes, that is quite possible. Have a look how OpenSSL FIPS 2.0.x did it
> > when
> 
> creating the fipscanister.o object.
> 
> When I've started working on my distro initially inheriting build procedures
> from Fedora. I just found that in openssl.spec is perfect example of use
> that using `rodata1` elf section ```spec
> # Add generation of HMAC checksum of the final stripped library
> # We manually copy standard definition of __spec_install_post
> # and add hmac calculation/embedding to fips.so
> %define __spec_install_post \
>         %{?__debug_package:%{__debug_install_post}} \
>         %{__arch_install_post} \
>         %{__os_install_post} \
>         LD_LIBRARY_PATH=. apps/openssl dgst -binary -sha256 -mac HMAC
> -macopt
> hexkey:f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813 <
> %{buildroot}%{_libdir}/ossl-modules/f ips.so >
> %{buildroot}%{_libdir}/ossl-modules/fips.so.hmac \
>         objcopy --update-section
> .rodata1=%{buildroot}%{_libdir}/ossl-modules/fips.so.hmac
> %{buildroot}%{_libdir}/ossl-modules/fips.so
> %{buildroot}%{_libdir}/ossl-modules/fips.so.mac \ %__mv
> %{buildroot}%{_libdir}/ossl-modules/fips.so.mac
> %{buildroot}%{_libdir}/ossl-modules/fips.so \ %__rm
> %{buildroot}%{_libdir}/ossl-modules/fips.so.hmac \
> %{nil}
> ```
> 
> FYI actually looks like easiest way to move back additional symlinks without
> patching is by use on install `make install DESTDIR=</install_prefix>
> pkglibexecdir=/usr/bin` .
> 
Sweet.

> PS. To be honest I'm not familiar with use signed binaries.
> (I don't want waste your time ..)
> Can you point on some descent documentation about how to use whole Linux
> based system with only signed binaries using FIPS?

Are you looking for EVM/IMA or dm-verity?

> 🤔  (examples of signing
> looks like I've already have and what is only missing is what needs to be
> changed in whole system/kernel and/or ls.so (probably? 🤔) side to always
> force verify FIPS signatures on execution or loading libraries and other
> DSOs) Or .. at least for what king of keywords I should be looking for
> searching using google? 🤔
> 
> Again .. thank you very much for the hint with openssl FIPS👍 😋


Ciao
Stephan

**Comment by kloczek** [comment]
> Are you looking for EVM/IMA or dm-verity?

Just finished quick look on EVM/IMA and looks like it uses extended attributes.
dm-verity seems is about devices protections.

I'm familiar a bit wit Solaris trusted extension which allows pass to the kernel load from TPM keyring (or load keyring from file over https after PXE boot) -> verify kernel image -> mount initrd -> verify each loaded into memory kernel modules using signatures and than continue work of the system with elf signatures verification (in kenel space) of all loaded and executed ELF binaries using each ELF file signatures.
So far I was not able to find something like this on Linux🤔 
I don't see as well what on Linux could use FIPS signs embedded in ELF sections .. so far seems like only openssl library is able to perform self verification however all that is done fully in user space.

**Comment by smuellerDD** [comment]
Am Montag, 23. Oktober 2023, 20:23:05 CEST schrieb Tomasz Kłoczko:

Hi Tomasz,

> > Are you looking for EVM/IMA or dm-verity?
> 
> Just finished quick look on EVM/IMA and looks like it uses extended
> attributes.

Yes, there you have some integrity check value.

> dm-verity seems is about devices protections.

Well, dm-verity is used by Android for the user space integrity enforcement.
> 
> I'm familiar a bit wit Solaris trusted extension which allows pass to the
> kernel load from TPM keyring (or load keyring from file over https after
> PXE boot) -> verify kernel image -> mount initrd -> verify each loaded into
> memory kernel modules using signatures and than continue work of the system
> with elf signatures verification (in kenel space) of all loaded and
> executed ELF binaries using each ELF file signatures. So far I was not able
> to find something like this on Linux🤔

Both would be addressed by EVM/IMA or dm-verity.

> I don't see as well what on Linux could use FIPS signs embedded in ELF
> sections .. so far seems like only openssl library is able to perform self
> verification however all that is done fully in user space.

For the aforementioned services, the integrity control values (signatures, 
HMACs) are in separate databases or the extended attribute. I am not aware 
that Linux has a generic means to store the control data in ELF sections as 
this would mean that there is a central system service that alters all 
executable files. And that would then violate rpm or dpkg-based integrity 
checks.


Ciao
Stephan
