### ISSUE TITLE
DRBG CAVP Issue

### ISSUE THREAD

**Issue by p870613** [smuellerDD/libkcapi#178]
Hi 

I want to pass cavp drbg, and trying some test vector in NIST
(ref:https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/random-number-generators)

I used this pattern
```
[SHA-1]
[PredictionResistance = False]
[EntropyInputLen = 128]
[NonceLen = 64]
[PersonalizationStringLen = 0]
[AdditionalInputLen = 0]
[ReturnedBitsLen = 640]

COUNT = 0
EntropyInput = 79349bbf7cdda5799557866621c91383
Nonce = 1146733abf8c35c8
PersonalizationString = 
** INSTANTIATE:
	V   = 4d9c202854ec825e28c032c0c1d8971f658a2b04
	Key = 900918d4a6f2a3e54f62a6b03bcf372de6f8b2a2
EntropyInputReseed = c7215b5b96c48e9b338c74e3e99dfedf
AdditionalInputReseed = 
** RESEED:
	V   = fa5315383a3e5e8e9591667982984353b7a0a8bf
	Key = 45467ed1cc9435d5a1683cec9d8533864ec58202
AdditionalInput = 
** GENERATE (FIRST CALL):
	V   = c0e51987773054629ee998cbab5e77478ba960c7
	Key = ea1ae579b6b071ffbda9d6fe2346c86a32b60a4c
AdditionalInput = 
ReturnedBits = c6a16ab8d420706f0f34ab7fec5adca9d8ca3a133e159ca6ac43c6f8a2be22834a4c0a0affb10d7194f1c1a5cf7322ec1ae0964ed4bf122746e087fdb5b3e91b3493d5bb98faed49e85f130fc8a459b7
** GENERATE (SECOND CALL):
	V   = f26b962d0e43a5587031297607079c387fc111f3
	Key = 2af498a9c9387c8cf02b552084cd3aafd23afd2f
```
This pattern require no_pr and reseed.

And, I meet some trouble that the `returnbits` isn't correct.

```=c
uint8_t ent[24] = "\x79\x34\x9b\xbf\x7c\xdd\xa5\x79\x95\x57\x86\x66\x21\xc9\x13\x83\x11\x46\x73\x3a\xbf\x8c\x35\xc8";
kcapi_rng_setentropy(rng, ent, 24); 
ret = kcapi_rng_seed(rng, seedbuf, seedsize); // Instantiate

uint8_t ent2[16] = "\xc7\x21\x5b\x5b\x96\xc4\x8e\x9b\x33\x8c\x74\xe3\xe9\x9d\xfe\xdf";
kcapi_rng_seed(rng, ent2, 16); //Reseed 

/*Generate Random Bits 2 times*/
while (count--) {
    int len = outlen;
    while (len) {
        size_t todo = (len < KCAPI_RNG_BUFSIZE) ? len : KCAPI_RNG_BUFSIZE;
        if (ret < 0)
            goto out;

        if ((uint32_t) ret == 0) {
            ret = -EFAULT;
            goto out;
        }

        if (hexout) {
            char hexbuf[2 * KCAPI_RNG_BUFSIZE];

            bin2hex(buf, (size_t) ret, hexbuf, sizeof(hexbuf), 0);
            fwrite(hexbuf, 2 * (size_t) ret, 1, stdout);
        } else {
            fwrite(buf, (size_t) ret, 1, stdout);
        }
        len -= (size_t) ret;
    }
    printf("\n");
}
```

Do you have some idea about this problem ? 
Thanks !!

**Comment by smuellerDD** [comment]
Am Montag, 6. November 2023, 04:49:40 CET schrieb p870613:

Hi p870613,

> Hi
> 
> I want to pass cavp drbg, and trying some test vector in NIST
> (ref:https://csrc.nist.gov/projects/cryptographic-algorithm-validation-progr
> am/random-number-generators)

With the standard AF_ALG interface wrapped by libkcapi you cannot test the 
DRBG because the DRBG always seeds itself from the entropy sources. Either you 
create a kernel module that circumnavigates the issue, or you use the special 
AF_ALG extension to test the DRBG (CRYPTO_USER_API_RNG_CAVP). In the latter 
case you need to enhance libkcapi to use the extended interface.
> 
> I used this pattern
> ```
> [SHA-1]
> [PredictionResistance = False]
> [EntropyInputLen = 128]
> [NonceLen = 64]
> [PersonalizationStringLen = 0]
> [AdditionalInputLen = 0]
> [ReturnedBitsLen = 640]
> 
> COUNT = 0
> EntropyInput = 79349bbf7cdda5799557866621c91383
> Nonce = 1146733abf8c35c8
> PersonalizationString =
> ** INSTANTIATE:
> 	V   = 4d9c202854ec825e28c032c0c1d8971f658a2b04
> 	Key = 900918d4a6f2a3e54f62a6b03bcf372de6f8b2a2
> EntropyInputReseed = c7215b5b96c48e9b338c74e3e99dfedf
> AdditionalInputReseed =
> ** RESEED:
> 	V   = fa5315383a3e5e8e9591667982984353b7a0a8bf
> 	Key = 45467ed1cc9435d5a1683cec9d8533864ec58202
> AdditionalInput =
> ** GENERATE (FIRST CALL):
> 	V   = c0e51987773054629ee998cbab5e77478ba960c7
> 	Key = ea1ae579b6b071ffbda9d6fe2346c86a32b60a4c
> AdditionalInput =
> ReturnedBits =
> c6a16ab8d420706f0f34ab7fec5adca9d8ca3a133e159ca6ac43c6f8a2be22834a4c0a0affb
> 10d7194f1c1a5cf7322ec1ae0964ed4bf122746e087fdb5b3e91b3493d5bb98faed49e85f130
> fc8a459b7 ** GENERATE (SECOND CALL):
> 	V   = f26b962d0e43a5587031297607079c387fc111f3
> 	Key = 2af498a9c9387c8cf02b552084cd3aafd23afd2f
> ```
> This pattern require no_pr and reseed.
> 
> And, I meet some trouble that the `returnbits` isn't correct.
> 
> ```=c
> uint8_t ent[24] =
> "\x79\x34\x9b\xbf\x7c\xdd\xa5\x79\x95\x57\x86\x66\x21\xc9\x13\x83\x11\x46\x
> 73\x3a\xbf\x8c\x35\xc8"; kcapi_rng_setentropy(rng, ent, 24);
> ret = kcapi_rng_seed(rng, seedbuf, seedsize); // Instantiate
> 
> uint8_t ent2[16] =
> "\xc7\x21\x5b\x5b\x96\xc4\x8e\x9b\x33\x8c\x74\xe3\xe9\x9d\xfe\xdf";
> kcapi_rng_seed(rng, ent2, 16); //Reseed
> 
> /*Generate Random Bits 2 times*/
> while (count--) {
>     int len = outlen;
>     while (len) {
>         size_t todo = (len < KCAPI_RNG_BUFSIZE) ? len : KCAPI_RNG_BUFSIZE;
>         if (ret < 0)
>             goto out;
> 
>         if ((uint32_t) ret == 0) {
>             ret = -EFAULT;
>             goto out;
>         }
> 
>         if (hexout) {
>             char hexbuf[2 * KCAPI_RNG_BUFSIZE];
> 
>             bin2hex(buf, (size_t) ret, hexbuf, sizeof(hexbuf), 0);
>             fwrite(hexbuf, 2 * (size_t) ret, 1, stdout);
>         } else {
>             fwrite(buf, (size_t) ret, 1, stdout);
>         }
>         len -= (size_t) ret;
>     }
>     printf("\n");
> }
> ```
> 
> Do you have some idea about this problem ?
> Thanks !!


Ciao
Stephan

**Comment by p870613** [comment]
Thank for your reply.
