### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [smuellerDD/libkcapi#18]
I find that [include guards like “`KCAPI_H`” and “`INTERNAL_H`” are too short](https://github.com/smuellerDD/libkcapi/commit/a9e1c1f49fb96d3b17f42b2d362327e78afc293c "Update candidate: rename header guards") for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by smuellerDD** [comment]
internal.h is, well, internal and never to be used outside the libkcapi/lib/ directory. Thus, any potential clash with have no visibility outside. Hence, I see no value in changing it.

Regarding kcapi.h, the guard uses the same letter string as the file name. If there is another kcapi.h, things will not compile anyway. Thus, using the guard name identical to the file name is save in my view. If you think it is unsafe, I would like to see a clash before changing
