### ISSUE TITLE
Undefined reference failure when building master branch

### ISSUE THREAD

**Issue by jijianwen** [smuellerDD/libkcapi#19]
My system info:
[jijianwen@dhcp-12-143 libkcapi]$ uname -r
4.8.15-200.fc24.x86_64
[jijianwen@dhcp-12-143 libkcapi]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --disable-libgcj --with-isl --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC)

libtool: link: gcc -fstack-protector-strong -g -O2 -Wl,-z -Wl,relro -Wl,-z -Wl,now -o bin/.libs/kcapi test/bin_kcapi-kcapi-main.o  ./.libs/libkcapi.so -Wl,-rpath -Wl,/usr/local/lib
test/bin_kcapi-kcapi-main.o: In function `kpp':
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2811: undefined reference to `kcapi_kpp_init'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2818: undefined reference to `kcapi_kpp_dh_setparam_pkcs3'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2826: undefined reference to `kcapi_kpp_ecdh_setcurve'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2834: undefined reference to `kcapi_kpp_setkey'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2852: undefined reference to `kcapi_kpp_ssgen'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2855: undefined reference to `kcapi_kpp_keygen'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2867: undefined reference to `kcapi_kpp_destroy'
test/bin_kcapi-kcapi-main.o: In function `kpp_aio':
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2884: undefined reference to `kcapi_kpp_init'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2891: undefined reference to `kcapi_kpp_dh_setparam_pkcs3'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2899: undefined reference to `kcapi_kpp_ecdh_setcurve'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2907: undefined reference to `kcapi_kpp_setkey'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2929: undefined reference to `kcapi_kpp_ssgen_aio'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2931: undefined reference to `kcapi_kpp_keygen_aio'
/home/jijianwen/wks/repos/libkcapi/test/kcapi-main.c:2943: undefined reference to `kcapi_kpp_destroy'
...
...

**Comment by smuellerDD** [comment]
I see that people want to copile the test application without using test-invocation.sh. The commit https://github.com/smuellerDD/libkcapi/commit/da825db388145ea096577d5118b61a03199bdaf4 should fix this issue.

**Comment by jijianwen** [comment]
@smuellerDD , it does work, thanks for your quick response!
