### ISSUE TITLE
FIPS requirement?

### ISSUE THREAD

**Issue by fijam** [smuellerDD/libkcapi#3]
Is the FIPS validation required? I think only Redhat/Centos (and maybe SUSE) went through the compliance program and provide /proc/sys/crypto/fips_enabled, which makes it difficult to easily test this library on other systems (like Debian) with the provided /apps/kcapi-hasher.

**Comment by smuellerDD** [comment]
Hi,

As this lieb does not implement any crypto it is not subjected to FIPS140. The kernel crypto API must  be validated. This is the case for RHEL and SLES.

Cui bono?

**Comment by fijam** [comment]
Sorry, I don't quite follow. The end users can test their kernel crypto driver correctness themselves with something like tcrypt, which is available in every distribution? Or is that insufficient?

Are you saying that exposing kernel crypto to userspace only makes sense on FIPS140-validated systems?

**Comment by smuellerDD** [comment]
Am Montag, 15. Februar 2016, 05:47:04 schrieb fijam:

Hi fijam,

> Sorry, I don't quite follow. The end users can test their kernel crypto
> driver correctness themselves with something like tcrypt, which is
> available in every distribution? Or is that insufficient?
> 
> Are you saying that exposing kernel crypto to userspace only makes sense on
> FIPS140-validated systems?

FIPS 140-2 applies to crypto implementations. As libkcapi has no crypto, it is 
not subjected to any FIPS 140-2 requirements. The kernel crypto API provides 
the cryptographic implementation and is therefore to be covered by FIPS 140-2 
validations.

A FIPS 140-2 validation of the kernel crypto API requires testmgr, but it 
requires much more than that for a successful validation.

And the kernel crypto API user space is needed for making hardware 
accelerators available to user space. All else is secondary.

Though, if you use the libkcapi HMAC check applications, then you implicitly 
add libkcapi into a FIPS 140-2 validation boundary and subject it to its 
rules. The only rule applicable to libkcapi and its HMAC application(s) is the 
integrity check that must be enforced.

Ciao
Stephan

**Comment by fijam** [comment]
I see, thanks for the clarification.
