### ISSUE TITLE
Can this tool be used on phones based on the ARM architecture?

### ISSUE THREAD

**Issue by openluopworld** [smuellerDD/libkcapi#32]
Can this tool be used on phones based on the ARM architecture? Thanks.

**Comment by smuellerDD** [comment]
Am Montag, 22. Januar 2018, 12:10:54 CET schrieb LuoPeng:

Hi LuoPeng,

> Can this tool be used on phones based on the ARM architecture? Thanks.

Sure, as long as the AF_ALG interface of the kernel is compiled, this library, 
the associated tools and any software using the lib can be executed on phones.

Ciao
Stephan
