### ISSUE TITLE
Makefile.am:20: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined

### ISSUE THREAD

**Issue by malaterre** [smuellerDD/libkcapi#34]
Just forwarding an issue which popup on Debian builds:

```
...
   dh_autoreconf -a -O--parallel
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:22: installing './compile'
configure.ac:22: installing './config.guess'
configure.ac:22: installing './config.sub'
configure.ac:21: installing './install-sh'
configure.ac:21: installing './missing'
Makefile.am: installing './depcomp'
Makefile.am:20: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined
autoreconf: automake failed with exit status: 1
dh_autoreconf: autoreconf -f -i returned exit code 1
debian/rules:8: recipe for target 'build-arch' failed
make: *** [build-arch] Error 2
```

Ref: https://buildd.debian.org/status/package.php?p=libkcapi&suite=sid

**Comment by malaterre** [comment]
Looks the issue is a missing depencie in the updated 1.0.3 package:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889879

> libkcapi ftbfs everywhere, missing b-d on pkgconfig?
> 
> https://buildd.debian.org/status/package.php?p=libkcapi
>

**Comment by smuellerDD** [comment]
Am Donnerstag, 8. Februar 2018, 14:39:00 CET schrieb Mathieu Malaterre:

Hi Mathieu,

> Looks the issue is a missing depencie in the updated 1.0.3 package:
> 
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889879

I do not fully understand this bug report. Are you missing a dependency in 
your Debian rules or do I miss something?
> 
> > libkcapi ftbfs everywhere, missing b-d on pkgconfig?
> > 
> > https://buildd.debian.org/status/package.php?p=libkcapi



Ciao
Stephan

**Comment by malaterre** [comment]
Right. I had missed the fact that `pkg-config` package is now required in 1.0.3 (not the case in 1.0.2). Sorry for the noise.

**Comment by TANK-RICHARD** [comment]
thanks, I miss the same question, and resolved by install pkg-config, 

sudo apt install -y pkg-config

**Comment by smuellerDD** [comment]
Do you have any suggestions on a change in the code base?
