### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by WOnder93** [smuellerDD/libkcapi#46]
Hi Stephan,

since there have now been a few bugfixes since v1.0.3, would you consider releasing a v1.0.4?

Thanks!

**Comment by smuellerDD** [comment]
Yes, but it will be a 1.1.0. I would like to conclude the discussion with the kernel crypto API maintainer for the code in the IIV branch.

At least the new API call of kcapi_handle_reinit should pop up in master.

If the kernel discussion cannot conclude fast, I will simply pick the kcapi_handle_reinit patch to master to release soon.
