### ISSUE TITLE
Qustion: keywrapping / trusted keyring support

### ISSUE THREAD

**Issue by ecki** [smuellerDD/libkcapi#77]
I wonder is there any support planned to pass in keys in a wrapped way, so the key handle becomes useable but you never can see the key unless you have the unwrapping key.

This can tie in with TPM (keyctrl trsted keys), Kernel Keyring and Secure Boot. (My specific usecase would be HMAC key for password storage.)

**Comment by smuellerDD** [comment]
Am Freitag, 8. März 2019, 19:07:35 CET schrieb Bernd:

Hi Bernd,

> I wonder is there any support planned to pass in keys in a wrapped way, so
> the key handle becomes useable but you never can see the key unless you
> have the unwrapping key.
> 
> This can tie in with TPM (keyctrl trsted keys), Kernel Keyring and Secure
> Boot. (My specific usecase would be HMAC key for password storage.)

This support is discussed and I have some patches that I need to process 
further.

Yet, there is no final plan whether or when that will be supported.

Ciao
Stephan

**Comment by ecki** [comment]
Thanks Stefan, if you want to run something by me for review or test let me know!
