### ISSUE TITLE
SHA and HMAC algs using patches

### ISSUE THREAD

**Issue by amrithathorath** [smuellerDD/libkcapi#85]
Is there a way where I can implement SHA and HMAC just like I did for AES (https://github.com/smuellerDD/libkcapi/issues/84#issuecomment-557570130) so that all my algs use similar method?

I tried implementing SHA with init, update and final calls and I see the following:

```
libkcapi - Error: Netlink error: cannot open netlink socket
libkcapi - Error: Netlink error: cannot open netlink socket
libkcapi - Error: NETLINK_CRYPTO: cannot obtain cipher information for sha1 (is required crypto_user.c patch missing? see documentation)
Segmentation fault
```

The code I had was:

```
kcapi_md_init(&handle, "sha1", 0);
kcapi_md_update(handle, params->msg, params->msgLength);
kcapi_md_final(handle, md, params->hashLength);
kcapi_md_destroy(handle);
```

**Comment by smuellerDD** [comment]
Am Dienstag, 26. November 2019, 20:27:51 CET schrieb amritha:

Hi amritha,

> Is there a way where I can implement SHA and HMAC just like I did for AES
> (https://github.com/smuellerDD/libkcapi/issues/84#issuecomment-557570130)
> so that all my algs use similar method?
> 
> I tried implementing SHA with init, update and final calls and I see the
> following:
> 
> ```
> libkcapi - Error: Netlink error: cannot open netlink socket
> libkcapi - Error: Netlink error: cannot open netlink socket
> libkcapi - Error: NETLINK_CRYPTO: cannot obtain cipher information for sha1
> (is required crypto_user.c patch missing? see documentation) Segmentation
> fault
> ```
> 
> The code I had was:
> 
> ```
> kcapi_md_init(&handle, "sha1", 0);
> kcapi_md_update(handle, params->msg, params->msgLength);
> kcapi_md_final(handle, md, params->hashLength);
> kcapi_md_destroy(handle);
> ```

You do not have CRYPTO_USER in the kernel. If you want libkcapi to be used, 
this kernel mechanism must be enabled as only this provides the details about 
a cipher to user space.

Ciao
Stephan

**Comment by amrithathorath** [comment]
@smuellerDD : Thanks a lot for that response.
I'm new to kernel testing, is there a link that you could point me to that describes how to enable CRYPTO_USER in kernel?

**Comment by smuellerDD** [comment]
Am Montag, 2. Dezember 2019, 16:01:08 CET schrieb amritha:

Hi amritha,

> @smuellerDD : Thanks a lot for that response.
> I'm new to kernel testing, is there a link that you could point me to that
> describes how to enable CRYPTO_USER in kernel?

You have to recompile the kernel

1. get the kernel

2. make menuconfig and select Crypto API -> Userspace cryptographic algorithm 
configuration

3. make && make modules_install install

4 reboot

Ciao
Stephan

**Comment by amrithathorath** [comment]
@smuellerDD : Thanks a lot for that...
