### ISSUE TITLE
Implementing DRBG (CAVP testing)

### ISSUE THREAD

**Issue by amrithathorath** [smuellerDD/libkcapi#86]
Stephan,

I'm trying to write some code to do CAVP testing for DRBG using the AF_ALG interface. Here is what I want to check with you.

1. As of now, these are my steps. Can you please confirm that I've not missed anything

```
kcapi_rng_init(&rng, rng_name, 0);

kcapi_rng_seed(rng, seedbuf, seedsize);

kcapi_rng_generate(rng, buf, todo);

kcapi_rng_generate(rng, buf, todo);
```

2. How do the parameters from CAVP request file get mapped here?
Sample input from request file:

```
EntropyInput = 3e5593deb25d8d5c8b90ad1211fbbdda
Nonce = 71f2d1d7a8253981
PersonalizationString =
AdditionalInput1 =
EntropyInputPR1 = 1c0e318fc9a14023f42b0cace6ae21ab
AdditionalInput1 =
EntropyInputPR2 = b477933991b9032be5103b5be011fddb
```

Here's my assumption. Please correct me if I'm wrong.
```
kcapi_rng_seed() - takes in EntropyInputReseed concatenated with AdditionalInputReseed
kcapi_rng_generate() - takes in EntropyInputPR1 concatenated with EntropyInputPR1 for first call
kcapi_rng_generate() - takes in EntropyInputPR2 concatenated with EntropyInputPR2 for first call
```

Not sure how EntropyInput, Nonce and PersonalizationString are used.

**Comment by smuellerDD** [comment]
Am Freitag, 13. Dezember 2019, 15:53:33 CET schrieb amritha:

Hi amritha,

> Stephan,
> 
> I'm trying to write some code to do CAVP testing for DRBG using the AF_ALG
> interface. Here is what I want to check with you.

You cannot. The DRBG is intended to be compliant to SP800-90A which mandates 
that the noise source is invoked by the DRBG.

The AF_ALG interface allows using the DRBG but not testing it as this would be 
a huge security issue. The data you provide with the seed call is effectively 
handled as the personalization / additional information string.

But you cannot set the entropy string or nonce with it.

If you want to test the kernel DRBG you have to write handling code similar to 
what is provided in crypto/testmgr.c:drbg_cavs_test().

> 
> 1. As of now, these are my steps. Can you please confirm that I've not
> missed anything
> 
> ```
> kcapi_rng_init(&rng, rng_name, 0);
> 
> kcapi_rng_seed(rng, seedbuf, seedsize);
> 
> kcapi_rng_generate(rng, buf, todo);
> 
> kcapi_rng_generate(rng, buf, todo);
> ```
> 
> 2. How do the parameters from CAVP request file get mapped here?
> Sample input from request file:
> 
> ```
> EntropyInput = 3e5593deb25d8d5c8b90ad1211fbbdda
> Nonce = 71f2d1d7a8253981
> PersonalizationString =
> AdditionalInput1 =
> EntropyInputPR1 = 1c0e318fc9a14023f42b0cace6ae21ab
> AdditionalInput1 =
> EntropyInputPR2 = b477933991b9032be5103b5be011fddb
> ```
> 
> Here's my assumption. Please correct me if I'm wrong.
> ```
> kcapi_rng_seed() - takes in EntropyInputReseed concatenated with
> AdditionalInputReseed kcapi_rng_generate() - takes in EntropyInputPR1
> concatenated with EntropyInputPR1 for first call kcapi_rng_generate() -
> takes in EntropyInputPR2 concatenated with EntropyInputPR2 for first call
> ```
> 
> Not sure how EntropyInput, Nonce and PersonalizationString are used.



Ciao
Stephan

**Comment by amrithathorath** [comment]
Thanks for the suggestion, will look into it.
