### ISSUE TITLE
Linux Kernel Crypto API User Space Interface limited to wmem,rmem size

### ISSUE THREAD

**Issue by mitulshah81** [smuellerDD/libkcapi#88]
Dear Sam,
We understand that you are active contributor to Linux Kernel Crypto API User Space Interface implementation in Linux Kernel we thought that you can share your views on the below observation.

Max. data that User Space Crypto Interface can send is limited with wmem_default. We observe that User Space is blocked (af_alg_wait_for_wmem) indefinitely with Zero Copy (splice) & Non-Zero Copy (sendmsg).
Is this known limitation? Could you share background of this limitation?
Could you share your thoughts on a solution approach to avoid a size limitation?

Thanks & Regards,
Mitul

**Comment by mitulshah81** [comment]
@smuellerDD Could you check?

**Comment by smuellerDD** [comment]
Am Donnerstag, 16. Januar 2020, 11:00:45 CET schrieb mitulshah81:

Hi mitulshah81,

> Dear Sam,
> We understand that you are active contributor to Linux Kernel Crypto API
> User Space Interface implementation in Linux Kernel we thought that you can
> share your views on the below observation.
> 
> Max. data that User Space Crypto Interface can send is limited with
> wmem_default. We observe that User Space is blocked (af_alg_wait_for_wmem)
> indefinitely with Zero Copy (splice) & Non-Zero Copy (sendmsg). Is this
> known limitation?

There is currently no known limitation or bug. The test code provided with 
libkcapi covers all permutations of possible types of user space requests.

Please provide a reproducer to allow debugging.

> Could you share background of this limitation? Could you
> share your thoughts on a solution approach to avoid a size limitation?
> 
> Thanks & Regards,
> Mitul


Ciao
Stephan

**Comment by mitulshah81** [comment]
@smuellerDD We have develop a test using libkcapi (modified libkcapi enc large test) which reproduce the issue (limited by socket wmem & rmem values). Kindly refer to kcapi-enc-test-large.c for test implementation.
Along with the test we have added log msg in Linux Kernel Crypto API User Space Interface & while executing the test we observe that indefinitely waits in af_alg_wait_for_wmem.

root@qemuarm64:~# kcapi-enc-test-large 300000
starting aead encrypt
[  616.066931] crypto/af_alg.c:834 Entry af_alg_sendmsg size=300000
[  616.067414] include/crypto/if_alg.h:183 sndbuf=212992 ctx->used=0
[  616.067673] include/crypto/if_alg.h:197 Number of bytes available to write 212992
[  616.069630] include/crypto/if_alg.h:183 sndbuf=212992 ctx->used=0
[  616.070541] include/crypto/if_alg.h:183 sndbuf=212992 ctx->used=212992
[  616.070788] include/crypto/if_alg.h:197 Number of bytes available to write 0
[  616.071043] crypto/af_alg.c:900 Not able to write so calling af_alg_wait_for_wmem
[  616.071382] Entry af_alg_wait_for_wmem
[  616.071571] waiting for wmem
[  616.071726] include/crypto/if_alg.h:183 sndbuf=212992 ctx->used=212992
[  616.075528] include/crypto/if_alg.h:197 Number of bytes available to write 0

I hope this helps.

Regards,
Mitul

**Comment by smuellerDD** [comment]
Sorry for the delay, too many programming jobs --- :-)

the success case is up to 212992 and it starts failing with 21293

**Comment by smuellerDD** [comment]
The issue is clear now and AF_ALG works as expected: The kernel enforces a limit of the socket read/write buffer which can be tweaked with /proc/sys/net/core/wmem_default and /proc/sys/net/core/rmem_default. For the issue in this report, wmem_default needs to be increased.

That is actually also quite clear: you use the one-shot API where the entire buffer to be encrypted is sent to the kernel. However, the kernel buffer to be used with sendmsg is too small where the AF_ALG waits for the rest of the data.

I think using the stream API offered by libkcapi should help here where you should ensure that the individual blocks are less than wmem_default / rmem_default.

**Comment by smuellerDD** [comment]
This is no bug, but a feature enforced by the kernel.
