### ISSUE TITLE
Usage of AES-XTS, what is the IV means here

### ISSUE THREAD

**Issue by BabaYB** [smuellerDD/libkcapi#89]
I wanna use xts(aes), but I don't konw the iv in the API, is that means sector num at here?

My code:
<img width="587" alt="code" src="https://user-images.githubusercontent.com/16234146/77649104-330c8680-6fa4-11ea-9f38-1b372b18cfcf.png">

Thanks

**Comment by smuellerDD** [comment]
Am Donnerstag, 26. März 2020, 13:55:18 CET schrieb BabaYB:

Hi BabaYB,

> I wanna use xts(aes), but I don't konw the iv in the API, is that means
> sector num at here?
> 
It is the tweak value or what you define as such like the sector number.

> My code:
> <img width="587" alt="GTScreenshot_20200326_205350"
> src="https://user-images.githubusercontent.com/16234146/77648976-fccf0700-6
> fa3-11ea-8fed-55559ed33254.png">
> 
> Thanks



Ciao
Stephan

**Comment by BabaYB** [comment]
Hi Stephan,

Yes, I got it, Thanks for your help!

Thanks,
