### ISSUE TITLE
Failed in using kacpi_cipher_enc_aes_cbc() with 256k data

### ISSUE THREAD

**Issue by BabaYB** [smuellerDD/libkcapi#90]
Hi all,
    
When I used the convenient api kacpi_cipher_enc_aes_cbc() to test my hardware crypt engine 
with different buffer size, but I got error when the data size was 256kB. And the other size 1k, 512k
works fine.

===============
Kernel version: 4.9
 
Code:

#define DATA_SIZE 256 * 1024
#define KEY_SIZE 128 / 16
#define IV_SIZE 128 / 16
data_buf = malloc(DATA_SIZE);
key_buf = malloc(KEY_SIZE);
iv_buf = malloc(IV_SIZE );
memset(key_buf, 'x', KEY_SIZE);
ret = kcapi_cipher_enc_aes_cbc(key_buf, KEY_SIZE, data_buf, DATA_SIZE，iv_buf, data_buf, DATA_SIZE );

and the ret is -22

===============
and  I traced in, the error return is occurred in kcapi-kernel-if.c:_kcapi_common_vmsplice_chunk()

===============
Further more, I modified the 'access' as KCAPI_ACCESSS_SENDMSG, and everything works fine now.

Thanks,
BabaYB

**Comment by smuellerDD** [comment]
Am Donnerstag, 2. April 2020, 14:56:43 CEST schrieb BabaYB:

Hi BabaYB,

> Hi all,
> 
>      When I used the convenient api kacpi_cipher_enc_aes_cbc() to test my
> hardware crypt engine with different buffer size, but I got error when the
> data size was 256kB. And the other size 1k, 512k
 works fine.
> 
> ===============
> Kernel version: 4.9
>  
> Code:
> 
> #define DATA_SIZE 256 * 1024
> #define KEY_SIZE 128 / 16
> #define IV_SIZE 128 / 16
> data_buf = malloc(DATA_SIZE);
> key_buf = malloc(KEY_SIZE);
> iv_buf = malloc(IV_SIZE );
> memset(key_buf, 'x', KEY_SIZE);
> ret = kcapi_cipher_enc_aes_cbc(key_buf, KEY_SIZE, data_buf,
> DATA_SIZE，iv_buf, data_buf, DATA_SIZE );
 
> and the ret is -22
> ===============
> and  I traced in, the error return is occurred in
> kcapi-kernel-if.c:_kcapi_common_vmsplice_chunk()
 
> ===============
> Further more, I modified the 'access' as KCAPI_ACCESSS_SENDMSG, and
> everything works fine now.

How interesting. _kcapi_common_vmsplice_chunk invokes sendmsg via the 
_kcapi_common_send_data if the input data is larger than 16 pages. 

What is your pagesize?
 
> Thanks,
> BabaYB
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/libkcapi/issues/90



Ciao
Stephan

**Comment by BabaYB** [comment]
Hi Stephan,

The page size is 4096.

I added more print at  _kcapi_common_vmsplice_chunk and We can see:

_kcapi_cipher_crypt_chunk: inlen 252144
_kcapi_cipher_crypt: inlen 65536
_kcapi_common_vmsplice_chunk : page_size 4096
_kcapi_common_vmsplice_chunk : handle->processed_sg 0
_kcapi_common_vmsplice_chunk : handle->flags.alg_max_pages 16
_kcapi_common_vmsplice_chunk : inlen 65536
_kcapi_common_vmsplice_chunk : vmsplice_limit 65536
_kcapi_common_vmsplice_chunk : ret of vmsplice 61568
_kcapi_common_vmsplice_chunk : ret of splice 61568
_kcapi_common_vmsplice_chunk : ret of vmsplice 3968
_kcapi_common_vmsplice_chunk : ret of splice -1

Thanks,
BabaYB

**Comment by smuellerDD** [comment]
Am Freitag, 3. April 2020, 04:54:46 CEST schrieb BabaYB:

Hi BabaYB,

> Hi Stephan,
> 
> The page size is 4096.

Could you please give it a try with 65535 bytes?
> 
> I added more print at  _kcapi_common_vmsplice_chunk and We can see:
> 
> _kcapi_cipher_crypt_chunk: inlen 252144
> _kcapi_cipher_crypt: inlen 65536
> _kcapi_common_vmsplice_chunk : page_size 4096
> _kcapi_common_vmsplice_chunk : handle->processed_sg 0
> _kcapi_common_vmsplice_chunk : handle->flags.alg_max_pages 16
> _kcapi_common_vmsplice_chunk : inlen 65536
> _kcapi_common_vmsplice_chunk : vmsplice_limit 65536
> _kcapi_common_vmsplice_chunk : ret of vmsplice 61568
> _kcapi_common_vmsplice_chunk : ret of splice 61568
> _kcapi_common_vmsplice_chunk : ret of vmsplice 3968
> _kcapi_common_vmsplice_chunk : ret of splice -1
> 
> Thanks,
> BabaYB



Ciao
Stephan

**Comment by BabaYB** [comment]
Hi Stephan,

I have tried 32K/ 64K/ 128K/ 196K/ 384K and the results are:

32K:
 _kcapi_cipher_crypt_chunk: inlen 32768
 _kcapi_common_vmsplice_chunk : handle->processed_sg 0
 _kcapi_common_vmsplice_chunk : handle->flags.alg_max_pages 16
 _kcapi_common_vmsplice_chunk : inlen 32768
 _kcapi_common_vmsplice_chunk : vmsplice_limit 65536
 _kcapi_common_vmsplice_chunk : ret of vmsplice 32768
 _kcapi_common_vmsplice_chunk : ret of splice 32768

64K:
 _kcapi_cipher_crypt_chunk: inlen 65536
 _kcapi_common_vmsplice_chunk : handle->processed_sg 0
 _kcapi_common_vmsplice_chunk : handle->flags.alg_max_pages 16
 _kcapi_common_vmsplice_chunk : inlen 65536
 _kcapi_common_vmsplice_chunk : vmsplice_limit 65536
 _kcapi_common_vmsplice_chunk : ret of vmsplice 62528
 _kcapi_common_vmsplice_chunk : ret of splice 62528
 _kcapi_common_vmsplice_chunk : ret of vmsplice 3008
 _kcapi_common_vmsplice_chunk : ret of splice -1

128K:
 _kcapi_cipher_crypt_chunk: inlen 131072
 _kcapi_common_vmsplice_chunk : handle->processed_sg 0
 _kcapi_common_vmsplice_chunk : handle->flags.alg_max_pages 16
 _kcapi_common_vmsplice_chunk : inlen 65536
 _kcapi_common_vmsplice_chunk : vmsplice_limit 65536
 _kcapi_common_vmsplice_chunk : ret of vmsplice 64768
 _kcapi_common_vmsplice_chunk : ret of splice 64768
 _kcapi_common_vmsplice_chunk : ret of vmsplice 768
 _kcapi_common_vmsplice_chunk : ret of splice -1

196K:
 _kcapi_cipher_crypt_chunk: inlen 200704
 _kcapi_common_vmsplice_chunk : handle->processed_sg 0
 _kcapi_common_vmsplice_chunk : handle->flags.alg_max_pages 16
 _kcapi_common_vmsplice_chunk : inlen 65536
 _kcapi_common_vmsplice_chunk : vmsplice_limit 65536
 _kcapi_common_vmsplice_chunk : ret of vmsplice 64768
 _kcapi_common_vmsplice_chunk : ret of splice 64768
 _kcapi_common_vmsplice_chunk : ret of vmsplice 768
 _kcapi_common_vmsplice_chunk : ret of splice -1

384K:
 _kcapi_cipher_crypt_chunk: inlen 393216
 _kcapi_common_vmsplice_chunk : handle->processed_sg 0
 _kcapi_common_vmsplice_chunk : handle->flags.alg_max_pages 16
 _kcapi_common_vmsplice_chunk : inlen 65536
 _kcapi_common_vmsplice_chunk : vmsplice_limit 65536
 _kcapi_common_vmsplice_chunk : ret of vmsplice 64768
 _kcapi_common_vmsplice_chunk : ret of splice 64768
 _kcapi_common_vmsplice_chunk : ret of vmsplice 768
 _kcapi_common_vmsplice_chunk : ret of splice -1

Thanks,
BabaYB

**Comment by smuellerDD** [comment]
The log seems to indicate that the _kcapi_common_vmsplice_chunk does not force the use of _kcapi_common_send_data for data > 16 pages on your kernel 4.9.

Can you please check what _kcapi_handle_flags sets handle->flags.alg_max_pages to?

```
/* older interfaces only processed 16 pages in a row */
	handle->flags.alg_max_pages = _kcapi_kernver_ge(handle, 4, 11, 0) ?
				      UINT_MAX : ALG_MAX_PAGES;
```

**Comment by smuellerDD** [comment]
I tested it on my systems and I am unable to reproduce it.

**Comment by smuellerDD** [comment]
If the issue persists, please report and reopen the issue.
