### ISSUE TITLE
Travis CI tags not showing up on new commits/PRs

### ISSUE THREAD

**Issue by WOnder93** [smuellerDD/libkcapi#95]
Could be the same issue as here: https://github.com/smuellerDD/libkcapi/pull/79#issuecomment-495100964

**Comment by smuellerDD** [comment]
It took a while, but the Travis status now shows success for me. Do you see that something else is missing?

**Comment by WOnder93** [comment]
For example, the commits are missing the usual green ticks:
https://github.com/smuellerDD/libkcapi/commits/master

The last commit that was tagged with CI success is the 1.1.5 release commit (5649050d201856bf06c8738b5d2aa1710c86ac2f).

**Comment by smuellerDD** [comment]
I asked the help desk.

**Comment by sahanaprasad07** [comment]
> I asked the help desk.

looks like the latest commit as the CI green tick.

**Comment by smuellerDD** [comment]
It took several rounds with the Travis-CI help desk as there were some issues. It seems to work now again.

**Comment by WOnder93** [comment]
Great, it also showed up correctly on the new PR (#97), so looks good now. Thanks!
