### ISSUE TITLE
Tests failing on the latest mainline kernel

### ISSUE THREAD

**Issue by WOnder93** [smuellerDD/libkcapi#99]
The libkcapi tests started failing all over the place on mainline kernel after the recent merge of Herbert's dev branch:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ab5c60b79ab6cc50b39bbb21b2f9fb55af900b84

I don't have time to dig further right now, but it should be easy to reproduce. Let me know if more details are needed.

**Comment by smuellerDD** [comment]
Am Dienstag, 4. August 2020, 19:26:17 CEST schrieb Ondrej Mosnáček:

Hi Ondrej,

> The libkcapi tests started failing all over the place on mainline kernel
> after the recent merge of Herbert's dev branch:
> https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?
> id=ab5c60b79ab6cc50b39bbb21b2f9fb55af900b84
> 
> I don't have time to dig further right now, but it should be easy to
> reproduce. Let me know if more details are needed.

Looking into it.

Ciao
Stephan

**Comment by WOnder93** [comment]
I found at least one issue:
https://lore.kernel.org/linux-crypto/20200812092232.364991-1-omosnace@redhat.com/T/

But even with that patch, some AEAD tests are still failing and one hangs indefinitely.

**Comment by smuellerDD** [comment]
Additional issue should be fixed with change b612c52c5ccf021d01e6c786db1a31a697f21d97.

**Comment by smuellerDD** [comment]
Closing as testing on latest kernel and earlier kernels show success.

**Comment by WOnder93** [comment]
I can confirm that b612c52 fixes the remaining failures for me as well. Thanks!
